import React from 'react';

const Sections = ({ type }) => {
    const items = [
        { number: '1', header: it.L('{JAPAN ONLY}Section 1: Structure') },
        { number: '2', header: it.L('{JAPAN ONLY}Section 2: Method') },
        { number: '3', header: it.L('{JAPAN ONLY}Section 3: Outline') },
        { number: '4', header: it.L('{JAPAN ONLY}Section 4: Risk') },
        { number: '5', header: it.L('{JAPAN ONLY}Section 5: Calculation') },
    ];
    return items.map(item => (
        <div key={item.number} id={`section${item.number}-${type}`}>
            <h2 className='gr-padding-10'>{item.header}</h2>
        </div>
    ));
};

const KnowledgeTest = () => (
    <div id='knowledge-test-container'>
        <h1 id='knowledge-test-header'>{it.L('{JAPAN ONLY}Knowledge Test')}</h1>
        <p id='knowledge-test-msg' />
        <div className='invisible' id='knowledge-test-instructions'>
            <ul className='bullet'>
                <li>{it.L('{JAPAN ONLY}Knowledge test list item 1')}</li>
                <li>{it.L('{JAPAN ONLY}Knowledge test list item 2')}</li>
                <li>{it.L('{JAPAN ONLY}Knowledge test list item 3')}</li>
                <li>{it.L('{JAPAN ONLY}Knowledge test list item 4')}</li>
                <li>{it.L('{JAPAN ONLY}Knowledge test list item 5')}</li>
            </ul>
        </div>
        <div id='knowledge-test-answer' className='invisible'>
            <Sections type='result' />
        </div>

        <div id='knowledge-test-questions' className='invisible'>
            <Sections type='question' />
            <div className='gr-centered gr-padding-10 center-text'>
                <p id='form-msg' className='error-msg invisible' />
                <button id='knowledge-test-submit' className='button'>{it.L('Submit')}</button>
            </div>
        </div>

        <div id='data-questions' className='invisible'>
            <div data-section-id='1'>
                <div data-question-id='1' data-tip={it.L('{JAPAN ONLY}TIP_1')} data-question-en='An option holder must buy ( or sell ) the underlying asset at a predetermined price within a specified period ( or at a specific time ).'>{it.L('{JAPAN ONLY}An option holder must buy ( or sell ) the underlying asset at a predetermined price within a specified period ( or at a specific time ).')}</div>
                <div data-question-id='2' data-tip={it.L('{JAPAN ONLY}TIP_2')} data-question-en='A Currency Option confers the right to sell one currency in exchange for another currency as the underlying asset. For example, the right to sell Yen and buy Dollars is known as a Yen Put / Dollar Call Option, or just Yen Put for short; and the opposite right to buy Yen and sell Dollar is called a Yen Call / Dollar Put Option, or just Yen Call for short.'>{it.L('{JAPAN ONLY}A Currency Option confers the right to sell one currency in exchange for another currency as the underlying asset. For example, the right to sell Yen and buy Dollars is known as a Yen Put / Dollar Call Option, or just Yen Put for short; and the opposite right to buy Yen and sell Dollar is called a Yen Call / Dollar Put Option, or just Yen Call for short.')}</div>
                <div data-question-id='3' data-tip={it.L('{JAPAN ONLY}TIP_3')} data-question-en='There are two types of option delivery: One requires exchanging the underlying asset, and the other requires a payment which depends on the difference between the fair market price and the exercise price. A Binary Option is the second type where if the fair market price meets certain conditions with respect to the exercise price, then an agreed fixed amount will be paid to the option buyer.'>{it.L('{JAPAN ONLY}There are two types of option delivery: One requires exchanging the underlying asset, and the other requires a payment which depends on the difference between the fair market price and the exercise price. A Binary Option is the second type where if the fair market price meets certain conditions with respect to the exercise price, then an agreed fixed amount will be paid to the option buyer.')}</div>
                <div data-question-id='4' data-tip={it.L('{JAPAN ONLY}TIP_4')} data-question-en='A  Net Settlement type of option is one where the underlying asset does not include yen, but the option fee and settlement are paid in yen; it therefore requires some definition of how the settlement amounts will be calculated and converted to yen.'>{it.L('{JAPAN ONLY}A  Net Settlement type of option is one where the underlying asset does not include yen, but the option fee and settlement are paid in yen; it therefore requires some definition of how the settlement amounts will be calculated and converted to yen.')}</div>
                <div data-question-id='5' data-tip={it.L('{JAPAN ONLY}TIP_5')} data-question-en='A Binary Option contains the right for the buyer to receive a certain fixed amount if the market price reaches the exercise price by the exercise time, but it does not contain any rights to sell or buy the underlying asset.'>{it.L('{JAPAN ONLY}A Binary Option contains the right for the buyer to receive a certain fixed amount if the market price reaches the exercise price by the exercise time, but it does not contain any rights to sell or buy the underlying asset.')}</div>
                <div data-question-id='6' data-tip={it.L('{JAPAN ONLY}TIP_6')} data-question-en='There are some types of Binary Option, such as Range Binary Options, Touch or No-Touch Binary Options, that are exceptions to the general rule where payment is made at a known exercise time. For these types of option a payment is made automatically at Exit Time when certain conditions have been met.'>{it.L('{JAPAN ONLY}There are some types of Binary Option, such as Range Binary Options, Touch or No-Touch Binary Options, that are exceptions to the general rule where payment is made at a known exercise time. For these types of option a payment is made automatically at Exit Time when certain conditions have been met.')}</div>
                <div data-question-id='7' data-tip={it.L('{JAPAN ONLY}TIP_7')} data-question-en='There are many types of Binary Option, including some such as Range Binary Options and Touch or No-Touch Binary Options which do not always require automatic payment at Exercise Time and which will be settled earlier if certain conditions have been met. However, in all cases, for a payment to be required, the option must end In The Money.'>{it.L('{JAPAN ONLY}There are many types of Binary Option, including some such as Range Binary Options and Touch or No-Touch Binary Options which do not always require automatic payment at Exercise Time and which will be settled earlier if certain conditions have been met. However, in all cases, for a payment to be required, the option must end In The Money.')}</div>
                <div data-question-id='8' data-tip={it.L('{JAPAN ONLY}TIP_8')} data-question-en='A Currency Binary Option is one where there is a target for a particular currency pair, so a strike price for the exchange rate is agreed, and a payout will be due if the judgment price meets the conditions of being over or under the target strike price, depending on the option type, by the exercise time.'>{it.L('{JAPAN ONLY}A Currency Binary Option is one where there is a target for a particular currency pair, so a strike price for the exchange rate is agreed, and a payout will be due if the judgment price meets the conditions of being over or under the target strike price, depending on the option type, by the exercise time.')}</div>
                <div data-question-id='9' data-tip={it.L('{JAPAN ONLY}TIP_9')} data-question-en='For a currency binary option which has the underlying exchange rate of dollars against yen, the right to receive a payout if the yen becomes weaker is known as a dollar-put binary option.'>{it.L('{JAPAN ONLY}For a currency binary option which has the underlying exchange rate of dollars against yen, the right to receive a payout if the yen becomes weaker is known as a dollar-put binary option.')}</div>
                <div data-question-id='10' data-tip={it.L('{JAPAN ONLY}TIP_10')} data-question-en='For a currency binary option with the underlying exchange rate of dollars against yen, the right to receive a payout if the yen becomes stronger is known as a dollar-put binary option.'>{it.L('{JAPAN ONLY}For a currency binary option with the underlying exchange rate of dollars against yen, the right to receive a payout if the yen becomes stronger is known as a dollar-put binary option.')}</div>
                <div data-question-id='11' data-tip={it.L('{JAPAN ONLY}TIP_11')} data-question-en='If you sell a currency binary call option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will need to payout 1,000 yen to the buyer of the option.'>{it.L('{JAPAN ONLY}If you sell a currency binary call option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will need to payout 1,000 yen to the buyer of the option.')}</div>
                <div data-question-id='12' data-tip={it.L('{JAPAN ONLY}TIP_12')} data-question-en='If you sell a currency binary put option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will need to payout 1,000 yen to the buyer of the option.'>{it.L('{JAPAN ONLY}If you sell a currency binary put option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will need to payout 1,000 yen to the buyer of the option.')}</div>
                <div data-question-id='13' data-tip={it.L('{JAPAN ONLY}TIP_13')} data-question-en='If you buy a currency binary call option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will receive a payout 1,000 yen from the seller of the option.'>{it.L('{JAPAN ONLY}If you buy a currency binary call option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will receive a payout 1,000 yen from the seller of the option.')}</div>
                <div data-question-id='14' data-tip={it.L('{JAPAN ONLY}TIP_14')} data-question-en='If you buy a currency binary put option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will receive a payout 1,000 yen from the seller of the option.'>{it.L('{JAPAN ONLY}If you buy a currency binary put option at a price of 500 yen, with an underlying of dollar against yen, the payout is 1,000 yen, and the strike price is 100, then if the judgment price at exercise time is 99, you will receive a payout 1,000 yen from the seller of the option.')}</div>
                <div data-question-id='15' data-tip={it.L('{JAPAN ONLY}TIP_15')} data-question-en='If you buy a currency binary option at a price of 500 yen, and the judgment price meets the conditions so you receive a payout of 1,000 yen, then your profit can be calculated 500 yen after subtracting the 500 yen that was paid as a fee to the option seller.'>{it.L('{JAPAN ONLY}If you buy a currency binary option at a price of 500 yen, and the judgment price meets the conditions so you receive a payout of 1,000 yen, then your profit can be calculated 500 yen after subtracting the 500 yen that was paid as a fee to the option seller.')}</div>
                <div data-question-id='16' data-tip={it.L('{JAPAN ONLY}TIP_16')} data-question-en='If you sell a currency binary option at a price of 500 yen, and the judgment price meets the conditions so you need to payout 1,000 yen, then your profit will be minus 500 yen after subtracting the 500 yen that was received as a fee from the option buyer.'>{it.L('{JAPAN ONLY}If you sell a currency binary option at a price of 500 yen, and the judgment price meets the conditions so you need to payout 1,000 yen, then your profit will be minus 500 yen after subtracting the 500 yen that was received as a fee from the option buyer.')}</div>
            </div>

            <div data-section-id='2'>
                <div data-question-id='17' data-tip={it.L('{JAPAN ONLY}TIP_17')} data-question-en='To avoid or hedge the future price of an underlying asset which you hold, you should buy a call option.'>{it.L('{JAPAN ONLY}To avoid or hedge the future price of an underlying asset which you hold, you should buy a call option.')}</div>
                <div data-question-id='18' data-tip={it.L('{JAPAN ONLY}TIP_18')} data-question-en='To compensate for any rise in the price of an underlying asset that you intend to buy in future, you should buy a call option.'>{it.L('{JAPAN ONLY}To compensate for any rise in the price of an underlying asset that you intend to buy in future, you should buy a call option.')}</div>
                <div data-question-id='19' data-tip={it.L('{JAPAN ONLY}TIP_19')} data-question-en='If you believe the underlying asset price will move by a large amount in either direction, you can benefit by buying both a call and a put option, with the exercise prices set above and below the current underlying price.'>{it.L('{JAPAN ONLY}If you believe the underlying asset price will move by a large amount in either direction, you can benefit by buying both a call and a put option, with the exercise prices set above and below the current underlying price.')}</div>
                <div data-question-id='20' data-tip={it.L('{JAPAN ONLY}TIP_20')} data-question-en='If you believe the underlying asset price will be only moderately volatile, you could still benefit by buying both a call and put option with exercise prices that are above and below the exercise price.'>{it.L('{JAPAN ONLY}If you believe the underlying asset price will be only moderately volatile, you could still benefit by buying both a call and put option with exercise prices that are above and below the exercise price.')}</div>
                <div data-question-id='21' data-tip={it.L('{JAPAN ONLY}TIP_21')} data-question-en='A Covered option position is where you hold an offsetting position in the underlying asset.'>{it.L('{JAPAN ONLY}A Covered option position is where you hold an offsetting position in the underlying asset.')}</div>
                <div data-question-id='22' data-tip={it.L('{JAPAN ONLY}TIP_22')} data-question-en='A binary call option buyer will benefit from a correct prediction that the asset price will decline to below the strike price by the judgment time.'>{it.L('{JAPAN ONLY}A binary call option buyer will benefit from a correct prediction that the asset price will decline to below the strike price by the judgment time.')}</div>
                <div data-question-id='23' data-tip={it.L('{JAPAN ONLY}TIP_23')} data-question-en='A binary put option buyer will benefit from a correct prediction that the asset price will decline to below the strike price by the judgment time.'>{it.L('{JAPAN ONLY}A binary put option buyer will benefit from a correct prediction that the asset price will decline to below the strike price by the judgment time.')}</div>
                <div data-question-id='24' data-tip={it.L('{JAPAN ONLY}TIP_24')} data-question-en='A binary put options buyer will benefit from a correct prediction that the asset price will rise above the strike price by the judgment time.'>{it.L('{JAPAN ONLY}A binary put options buyer will benefit from a correct prediction that the asset price will rise above the strike price by the judgment time.')}</div>
                <div data-question-id='25' data-tip={it.L('{JAPAN ONLY}TIP_25')} data-question-en='A binary call options buyer will benefit from a correct prediction that the asset price will rise above the strike price by the judgment time.'>{it.L('{JAPAN ONLY}A binary call options buyer will benefit from a correct prediction that the asset price will rise above the strike price by the judgment time.')}</div>
                <div data-question-id='26' data-tip={it.L('{JAPAN ONLY}TIP_26')} data-question-en='When buying a vanilla call option, the break-even price at the exercise point is the strike price plus the option price paid in units of the underlying.'>{it.L('{JAPAN ONLY}When buying a vanilla call option, the break-even price at the exercise point is the strike price plus the option price paid in units of the underlying.')}</div>
                <div data-question-id='27' data-tip={it.L('{JAPAN ONLY}TIP_27')} data-question-en='When buying a vanilla put option, the break-even price at the exercise point is the strike price minus the option price paid in units of the underlying.'>{it.L('{JAPAN ONLY}When buying a vanilla put option, the break-even price at the exercise point is the strike price minus the option price paid in units of the underlying.')}</div>
                <div data-question-id='28' data-tip={it.L('{JAPAN ONLY}TIP_28')} data-question-en='Using binary options for hedging a position in the underlying asset means that only part of the loss or gain can be hedged, because the payout amount is fixed.'>{it.L('{JAPAN ONLY}Using binary options for hedging a position in the underlying asset means that only part of the loss or gain can be hedged, because the payout amount is fixed.')}</div>
                <div data-question-id='29' data-tip={it.L('{JAPAN ONLY}TIP_29')} data-question-en='It is possible to use two binary options to make a profit if the asset price settles inbetween the two strikes. It is also possible to buy a single range option that will achieve the same result.'>{it.L('{JAPAN ONLY}It is possible to use two binary options to make a profit if the asset price settles inbetween the two strikes. It is also possible to buy a single range option that will achieve the same result.')}</div>
                <div data-question-id='30' data-tip={it.L('{JAPAN ONLY}TIP_30')} data-question-en='It is possible to use two binary options to make a profit if the asset price settles outside the two strikes. It is also possible to buy a single range option that will achieve the same result.'>{it.L('{JAPAN ONLY}It is possible to use two binary options to make a profit if the asset price settles outside the two strikes. It is also possible to buy a single range option that will achieve the same result.')}</div>
            </div>

            <div data-section-id='3'>
                <div data-question-id='31' data-tip={it.L('{JAPAN ONLY}TIP_31')} data-question-en='In Japan there are defined trading periods for binary options must be 2 hours or longer, and all trades must be conducted at the start of each trading period.'>{it.L('{JAPAN ONLY}In Japan there are defined trading periods for binary options must be 2 hours or longer, and all trades must be conducted at the start of each trading period.')}</div>
                <div data-question-id='32' data-tip={it.L('{JAPAN ONLY}TIP_32')} data-question-en='A bought or sold binary option may be closed-out before exercise time by selling or buying-back the option, or alternatively by cancelling.'>{it.L('{JAPAN ONLY}A bought or sold binary option may be closed-out before exercise time by selling or buying-back the option, or alternatively by cancelling.')}</div>
                <div data-question-id='33' data-tip={it.L('{JAPAN ONLY}TIP_33')} data-question-en='In contrast to other types of FX options, short positions in FX Binary Options cannot be closed-out as they are not subject to loss-cut regulations.'>{it.L('{JAPAN ONLY}In contrast to other types of FX options, short positions in FX Binary Options cannot be closed-out as they are not subject to loss-cut regulations.')}</div>
                <div data-question-id='34' data-tip={it.L('{JAPAN ONLY}TIP_34')} data-question-en='Short positions in FX Binary Options must be covered by initial margin and any further losses must be covered by further margin deposits.'>{it.L('{JAPAN ONLY}Short positions in FX Binary Options must be covered by initial margin and any further losses must be covered by further margin deposits.')}</div>
                <div data-question-id='35' data-tip={it.L('{JAPAN ONLY}TIP_35')} data-question-en={'Although customers and brokers will set limits on customers trading losses, even if those losses are exceeded, it is the customer\'s responsibility to close the position and so mandatory loss-cuts will not be executed by the broker company.'}>{it.L('{JAPAN ONLY}Although customers and brokers will set limits on customers trading losses, even if those losses are exceeded, it is the customer\'s responsibility to close the position and so mandatory loss-cuts will not be executed by the broker company.')}</div>
                <div data-question-id='36' data-tip={it.L('{JAPAN ONLY}TIP_36')} data-question-en='Options may be European or American style of exercise, and those which can be exercised at only one expiry time are the European style options.'>{it.L('{JAPAN ONLY}Options may be European or American style of exercise, and those which can be exercised at only one expiry time are the European style options.')}</div>
                <div data-question-id='37' data-tip={it.L('{JAPAN ONLY}TIP_37')} data-question-en='For a call option, if the price of the underlying asset is higher than the option exercise price, it is know as an in-the-money option.'>{it.L('{JAPAN ONLY}For a call option, if the price of the underlying asset is higher than the option exercise price, it is know as an in-the-money option.')}</div>
                <div data-question-id='38' data-tip={it.L('{JAPAN ONLY}TIP_38')} data-question-en='For a call option, if the price of the underlying asset is higher than the option exercise price, it is know as an out-of-the-money option.'>{it.L('{JAPAN ONLY}For a call option, if the price of the underlying asset is higher than the option exercise price, it is know as an out-of-the-money option.')}</div>
                <div data-question-id='39' data-tip={it.L('{JAPAN ONLY}TIP_39')} data-question-en='For both call and put options, if the underlying asset price is the same as the exercise price, it is known as an at-the-money option.'>{it.L('{JAPAN ONLY}For both call and put options, if the underlying asset price is the same as the exercise price, it is known as an at-the-money option.')}</div>
                <div data-question-id='40' data-tip={it.L('{JAPAN ONLY}TIP_40')} data-question-en='For a put option, if the underlying asset price is lower than the option exercise price, it is known as an out-of-the-money option.'>{it.L('{JAPAN ONLY}For a put option, if the underlying asset price is lower than the option exercise price, it is known as an out-of-the-money option.')}</div>
                <div data-question-id='41' data-tip={it.L('{JAPAN ONLY}TIP_41')} data-question-en='For a put option, if the underlying asset price is higher than the option exercise price, it is known as an in-the-money option.'>{it.L('{JAPAN ONLY}For a put option, if the underlying asset price is higher than the option exercise price, it is known as an in-the-money option.')}</div>
                <div data-question-id='42' data-tip={it.L('{JAPAN ONLY}TIP_42')} data-question-en='The Exercise Price is the level at which the option buyer has the right to trade the underlying, and is also used for binary options to determine whether the buyer should receive a payout.'>{it.L('{JAPAN ONLY}The Exercise Price is the level at which the option buyer has the right to trade the underlying, and is also used for binary options to determine whether the buyer should receive a payout.')}</div>
                <div data-question-id='43' data-tip={it.L('{JAPAN ONLY}TIP_43')} data-question-en='The Exit Price is the price that is observed at the judgment time, and is used to determine whether a payout should be made.'>{it.L('{JAPAN ONLY}The Exit Price is the price that is observed at the judgment time, and is used to determine whether a payout should be made.')}</div>
                <div data-question-id='44' data-tip={it.L('{JAPAN ONLY}TIP_44')} data-question-en='The payout is the amount that the option seller must pay to the buyer if the buyer exercises his right when the conditions for a payout have been satisfied.'>{it.L('{JAPAN ONLY}The payout is the amount that the option seller must pay to the buyer if the buyer exercises his right when the conditions for a payout have been satisfied.')}</div>
                <div data-question-id='45' data-tip={it.L('{JAPAN ONLY}TIP_45')} data-question-en='In OTC currency binary options trading, if the exchange rate during the trading period moves by more than expected in one direction, and there are no longer any exercise prices which can continue to trade, it is possible under certain conditions to add further exercise prices. However, even when further exercise price have been added, the prices of the original options will not be affected.'>{it.L('{JAPAN ONLY}In OTC currency binary options trading, if the exchange rate during the trading period moves by more than expected in one direction, and there are no longer any exercise prices which can continue to trade, it is possible under certain conditions to add further exercise prices. However, even when further exercise price have been added, the prices of the original options will not be affected.')}</div>
                <div data-question-id='46' data-tip={it.L('{JAPAN ONLY}TIP_46')} data-question-en='The exit price is important in binary options. In case of handling the OTC currency-related binary options trading for private individuals, the broker company must perform inspections of the exit prices which have been used for determining option payout, and must check whether there is an error in the data in cases where that the company has used rated data provided by third company.'>{it.L('{JAPAN ONLY}The exit price is important in binary options. In case of handling the OTC currency-related binary options trading for private individuals, the broker company must perform inspections of the exit prices which have been used for determining option payout, and must check whether there is an error in the data in cases where that the company has used rated data provided by third company.')}</div>
                <div data-question-id='47' data-tip={it.L('{JAPAN ONLY}TIP_47')} data-question-en={'About OTC currency for binary options trading, summarizes the profit and loss result of all transactions that have been made between the customer, to publish the information in the company\'s home page, at any time while the customer is doing the transaction before the start, or the transaction, the information Make sure, for that you\'re willing to trade under the calm judgment, we are committed to a variety of environmental improvement.'}>{it.L('{JAPAN ONLY}About OTC currency for binary options trading, summarizes the profit and loss result of all transactions that have been made between the customer, to publish the information in the company\'s home page, at any time while the customer is doing the transaction before the start, or the transaction, the information Make sure, for that you\'re willing to trade under the calm judgment, we are committed to a variety of environmental improvement.')}</div>
                <div data-question-id='48' data-tip={it.L('{JAPAN ONLY}TIP_48')} data-question-en='For an individual investor, all profits from OTC currency options trading are tax-free.'>{it.L('{JAPAN ONLY}For an individual investor, all profits from OTC currency options trading are tax-free.')}</div>
                <div data-question-id='49' data-tip={it.L('{JAPAN ONLY}TIP_49')} data-question-en='For an individual investor, profits and losses from OTC currency options traing cannot be combined with profits and losses from margin FX and securities-related OTC options.'>{it.L('{JAPAN ONLY}For an individual investor, profits and losses from OTC currency options traing cannot be combined with profits and losses from margin FX and securities-related OTC options.')}</div>
                <div data-question-id='50' data-tip={it.L('{JAPAN ONLY}TIP_50')} data-question-en='Unless special arrangements are made, cooling-off will not be available after OTC binary options trading contract has been made.'>{it.L('{JAPAN ONLY}Unless special arrangements are made, cooling-off will not be available after OTC binary options trading contract has been made.')}</div>
            </div>

            <div data-section-id='4'>
                <div data-question-id='51' data-tip={it.L('{JAPAN ONLY}TIP_51')} data-question-en='If the buyer of an option does not exercise the option rights, there will be no fee payable to the option seller.'>{it.L('{JAPAN ONLY}If the buyer of an option does not exercise the option rights, there will be no fee payable to the option seller.')}</div>
                <div data-question-id='52' data-tip={it.L('{JAPAN ONLY}TIP_52')} data-question-en='If the buyer of an option waives his right to exercise, a transaction in the underlying asset will not be dealt between the seller and the buyer.'>{it.L('{JAPAN ONLY}If the buyer of an option waives his right to exercise, a transaction in the underlying asset will not be dealt between the seller and the buyer.')}</div>
                <div data-question-id='53' data-tip={it.L('{JAPAN ONLY}TIP_53')} data-question-en='The seller of an option should receive the option premium from the buyer, even if the buyer waives the right to exercise the option.'>{it.L('{JAPAN ONLY}The seller of an option should receive the option premium from the buyer, even if the buyer waives the right to exercise the option.')}</div>
                <div data-question-id='54' data-tip={it.L('{JAPAN ONLY}TIP_54')} data-question-en='If an option buyer wishes to exercise the option rights, the seller may still reject the deal.'>{it.L('{JAPAN ONLY}If an option buyer wishes to exercise the option rights, the seller may still reject the deal.')}</div>
                <div data-question-id='55' data-tip={it.L('{JAPAN ONLY}TIP_55')} data-question-en='Options are said to be leveraged products because in the case of large moves in the underlying asset price, the values of the options can increase by large amounts compared to the price paid for the option.'>{it.L('{JAPAN ONLY}Options are said to be leveraged products because in the case of large moves in the underlying asset price, the values of the options can increase by large amounts compared to the price paid for the option.')}</div>
                <div data-question-id='56' data-tip={it.L('{JAPAN ONLY}TIP_56')} data-question-en='The buyer of a vanilla option can choose whether to exercise the option or not. His loss is limited to the price paid for the option, whereas his potential profit is unlimited.'>{it.L('{JAPAN ONLY}The buyer of a vanilla option can choose whether to exercise the option or not. His loss is limited to the price paid for the option, whereas his potential profit is unlimited.')}</div>
                <div data-question-id='57' data-tip={it.L('{JAPAN ONLY}TIP_57')} data-question-en='The seller of a vanilla option can not choose whether to exercise the option or not. His profit is limited to the price received for the option, whereas his potential loss is unlimited and could be substantial.'>{it.L('{JAPAN ONLY}The seller of a vanilla option can not choose whether to exercise the option or not. His profit is limited to the price received for the option, whereas his potential loss is unlimited and could be substantial.')}</div>
                <div data-question-id='58' data-tip={it.L('{JAPAN ONLY}TIP_58')} data-question-en='If the exercise period passes without the option being exercised by the buyer, the option premium received by the seller will be the profit made on the trade.'>{it.L('{JAPAN ONLY}If the exercise period passes without the option being exercised by the buyer, the option premium received by the seller will be the profit made on the trade.')}</div>
                <div data-question-id='59' data-tip={it.L('{JAPAN ONLY}TIP_59')} data-question-en='Even if the option is exercise or not exercised, the original option premium remains with the option seller.'>{it.L('{JAPAN ONLY}Even if the option is exercise or not exercised, the original option premium remains with the option seller.')}</div>
                <div data-question-id='60' data-tip={it.L('{JAPAN ONLY}TIP_60')} data-question-en='The maximum loss for the buyer of an option is the price paid, and the maximium loss for the option seller will be the payout amount minus the opion price he received.'>{it.L('{JAPAN ONLY}The maximum loss for the buyer of an option is the price paid, and the maximium loss for the option seller will be the payout amount minus the opion price he received.')}</div>
                <div data-question-id='61' data-tip={it.L('{JAPAN ONLY}TIP_61')} data-question-en='Because option prices are determined by the probability of being exercised, it cannot be said that cheaper options have any natural advantage over expensive options.'>{it.L('{JAPAN ONLY}Because option prices are determined by the probability of being exercised, it cannot be said that cheaper options have any natural advantage over expensive options.')}</div>
                <div data-question-id='62' data-tip={it.L('{JAPAN ONLY}TIP_62')} data-question-en='Binary options have lower risk than vanilla options for option sellers, because with binary options the maximum loss is fixed.'>{it.L('{JAPAN ONLY}Binary options have lower risk than vanilla options for option sellers, because with binary options the maximum loss is fixed.')}</div>
                <div data-question-id='63' data-tip={it.L('{JAPAN ONLY}TIP_63')} data-question-en='Even though losses in binary options are limited, it is still necessary to take care not to engage in excessive speculative trading and to moderate your transactions volume.'>{it.L('{JAPAN ONLY}Even though losses in binary options are limited, it is still necessary to take care not to engage in excessive speculative trading and to moderate your transactions volume.')}</div>
                <div data-question-id='64' data-tip={it.L('{JAPAN ONLY}TIP_64')} data-question-en='If the probablility of a payout is 50% then when the potential payout is less than 100% of the price paid for the option, the expected return on the investment will be less than 100%.'>{it.L('{JAPAN ONLY}If the probablility of a payout is 50% then when the potential payout is less than 100% of the price paid for the option, the expected return on the investment will be less than 100%.')}</div>
                <div data-question-id='65' data-tip={it.L('{JAPAN ONLY}TIP_65')} data-question-en='It cannot be said that binary options trading is unconditionally advanteous over regular spot fx trading, because investors may lose all of their investment whereas in spot fx trading there will still be some value in the trading position.'>{it.L('{JAPAN ONLY}It cannot be said that binary options trading is unconditionally advanteous over regular spot fx trading, because investors may lose all of their investment whereas in spot fx trading there will still be some value in the trading position.')}</div>
                <div data-question-id='66' data-tip={it.L('{JAPAN ONLY}TIP_66')} data-question-en='The particular details of binary options are all the same, no matter which broking company you trade with.'>{it.L('{JAPAN ONLY}The particular details of binary options are all the same, no matter which broking company you trade with.')}</div>
                <div data-question-id='67' data-tip={it.L('{JAPAN ONLY}TIP_67')} data-question-en='Even if all details of the binary options match perfectly, there may still be differences in the prices shown by different broking companies.'>{it.L('{JAPAN ONLY}Even if all details of the binary options match perfectly, there may still be differences in the prices shown by different broking companies.')}</div>
                <div data-question-id='68' data-tip={it.L('{JAPAN ONLY}TIP_68')} data-question-en='Prices for currency options are calculated relative the value of theunderlying spot price, and are dependant on multiple factors which may vary.'>{it.L('{JAPAN ONLY}Prices for currency options are calculated relative the value of theunderlying spot price, and are dependant on multiple factors which may vary.')}</div>
                <div data-question-id='69' data-tip={it.L('{JAPAN ONLY}TIP_69')} data-question-en='Where broking companies show bid and offer prices for purchasing and sell-back of positions, these prices may become further apart the nearer you are to the exercise time.'>{it.L('{JAPAN ONLY}Where broking companies show bid and offer prices for purchasing and sell-back of positions, these prices may become further apart the nearer you are to the exercise time.')}</div>
                <div data-question-id='70' data-tip={it.L('{JAPAN ONLY}TIP_70')} data-question-en='Option prices depend on the spot price, the time to expiry, the volatility of the spot rate and interest rates.'>{it.L('{JAPAN ONLY}Option prices depend on the spot price, the time to expiry, the volatility of the spot rate and interest rates.')}</div>
            </div>

            <div data-section-id='5'>
                <div data-question-id='71' data-tip={it.L('{JAPAN ONLY}TIP_71')} data-question-en='The price of an option can be affected by the underlying asset price, by the volatility rate of the underlying asset, or by the time remaining to the exercise time.'>{it.L('{JAPAN ONLY}The price of an option can be affected by the underlying asset price, by the volatility rate of the underlying asset, or by the time remaining to the exercise time.')}</div>
                <div data-question-id='72' data-tip={it.L('{JAPAN ONLY}TIP_72')} data-question-en='The price of a vanilla call option will be lower when price of the underlying asset is low, but the price of the put option will be higher when the price of the underlying asset is low.'>{it.L('{JAPAN ONLY}The price of a vanilla call option will be lower when price of the underlying asset is low, but the price of the put option will be higher when the price of the underlying asset is low.')}</div>
                <div data-question-id='73' data-tip={it.L('{JAPAN ONLY}TIP_73')} data-question-en='If the exercise prices and exercise times are the same for an American style and European style option, then the American style option will have a higher price.'>{it.L('{JAPAN ONLY}If the exercise prices and exercise times are the same for an American style and European style option, then the American style option will have a higher price.')}</div>
                <div data-question-id='74' data-tip={it.L('{JAPAN ONLY}TIP_74')} data-question-en='In case of the right to buy the underlying asset (call option), when the underlying asset price falls, the option price will increase.'>{it.L('{JAPAN ONLY}In case of the right to buy the underlying asset (call option), when the underlying asset price falls, the option price will increase.')}</div>
                <div data-question-id='75' data-tip={it.L('{JAPAN ONLY}TIP_75')} data-question-en='In case of the right to sell the underlying asset (put option), when the underlying asset price rises, the option price will increase.'>{it.L('{JAPAN ONLY}In case of the right to sell the underlying asset (put option), when the underlying asset price rises, the option price will increase.')}</div>
                <div data-question-id='76' data-tip={it.L('{JAPAN ONLY}TIP_76')} data-question-en='For an out-of-the-money option, the further away from the underlying asset price that the option exercise price is, the lower the price of the option will be.'>{it.L('{JAPAN ONLY}For an out-of-the-money option, the further away from the underlying asset price that the option exercise price is, the lower the price of the option will be.')}</div>
                <div data-question-id='77' data-tip={it.L('{JAPAN ONLY}TIP_77')} data-question-en='For an in-the-money option, the further away from the underlying asset price that the option exercise price is, the lower the price of the option will be.'>{it.L('{JAPAN ONLY}For an in-the-money option, the further away from the underlying asset price that the option exercise price is, the lower the price of the option will be.')}</div>
                <div data-question-id='78' data-tip={it.L('{JAPAN ONLY}TIP_78')} data-question-en='If implied volatility increases then the prices of both call and put types of plain vanilla options will increase.'>{it.L('{JAPAN ONLY}If implied volatility increases then the prices of both call and put types of plain vanilla options will increase.')}</div>
                <div data-question-id='79' data-tip={it.L('{JAPAN ONLY}TIP_79')} data-question-en='As the expected volatility of the underlying asset increases, a plain vanilla option price will move higher.'>{it.L('{JAPAN ONLY}As the expected volatility of the underlying asset increases, a plain vanilla option price will move higher.')}</div>
                <div data-question-id='80' data-tip={it.L('{JAPAN ONLY}TIP_80')} data-question-en='For a plain vanilla option, as the time to the exercise point shortens, the price of the option will decrease.'>{it.L('{JAPAN ONLY}For a plain vanilla option, as the time to the exercise point shortens, the price of the option will decrease.')}</div>
                <div data-question-id='81' data-tip={it.L('{JAPAN ONLY}TIP_81')} data-question-en='An option price is the sum of the intrinsic-value and the time-value.'>{it.L('{JAPAN ONLY}An option price is the sum of the intrinsic-value and the time-value.')}</div>
                <div data-question-id='82' data-tip={it.L('{JAPAN ONLY}TIP_82')} data-question-en={'If the underlying asset price is 100 yen, the exercise price is 80 yen, and the call option price is 45 yen, then it can be said that the option\'s intrinsic-value is 20 yen, and its time-value is 25 yen.'}>{it.L('{JAPAN ONLY}If the underlying asset price is 100 yen, the exercise price is 80 yen, and the call option price is 45 yen, then it can be said that the option\'s intrinsic-value is 20 yen, and its time-value is 25 yen.')}</div>
                <div data-question-id='83' data-tip={it.L('{JAPAN ONLY}TIP_83')} data-question-en='The time-value of an option represents the expected value of the option at the exercise point, and may be positive, even when the intrinsic-value is zero.'>{it.L('{JAPAN ONLY}The time-value of an option represents the expected value of the option at the exercise point, and may be positive, even when the intrinsic-value is zero.')}</div>
                <div data-question-id='84' data-tip={it.L('{JAPAN ONLY}TIP_84')} data-question-en='As the time to the exercise point shortens, the time-value of a plain vanilla option decreases.'>{it.L('{JAPAN ONLY}As the time to the exercise point shortens, the time-value of a plain vanilla option decreases.')}</div>
                <div data-question-id='85' data-tip={it.L('{JAPAN ONLY}TIP_85')} data-question-en='A binary option price cannot exceed the payout amount.'>{it.L('{JAPAN ONLY}A binary option price cannot exceed the payout amount.')}</div>
                <div data-question-id='86' data-tip={it.L('{JAPAN ONLY}TIP_86')} data-question-en='In general a binary option price will not exceed the payout amount.'>{it.L('{JAPAN ONLY}In general a binary option price will not exceed the payout amount.')}</div>
                <div data-question-id='87' data-tip={it.L('{JAPAN ONLY}TIP_87')} data-question-en='Unlike a plain vanilla option, an in-the-money binary option will have a lower price, the further away it is from the exercise point.'>{it.L('{JAPAN ONLY}Unlike a plain vanilla option, an in-the-money binary option will have a lower price, the further away it is from the exercise point.')}</div>
                <div data-question-id='88' data-tip={it.L('{JAPAN ONLY}TIP_88')} data-question-en='In general the price of a binary option will be lower than the price of a plain vanilla option because the payout amount is fixed.'>{it.L('{JAPAN ONLY}In general the price of a binary option will be lower than the price of a plain vanilla option because the payout amount is fixed.')}</div>
                <div data-question-id='89' data-tip={it.L('{JAPAN ONLY}TIP_89')} data-question-en='A binary option which is out-of-the-money will have a lower price than an option which is in-the-money because the probability of receiving the payout amount is lower.'>{it.L('{JAPAN ONLY}A binary option which is out-of-the-money will have a lower price than an option which is in-the-money because the probability of receiving the payout amount is lower.')}</div>
                <div data-question-id='90' data-tip={it.L('{JAPAN ONLY}TIP_90')} data-question-en='A binary option which is in-the-money will have a higher value than an option that is out-of-the-money because there will be a higher probability of receiving the payout amount.'>{it.L('{JAPAN ONLY}A binary option which is in-the-money will have a higher value than an option that is out-of-the-money because there will be a higher probability of receiving the payout amount.')}</div>
                <div data-question-id='91' data-tip={it.L('{JAPAN ONLY}TIP_91')} data-question-en='As the exercise deadline approaches, the price of an in-the-money binary option will move towards the payout amount.'>{it.L('{JAPAN ONLY}As the exercise deadline approaches, the price of an in-the-money binary option will move towards the payout amount.')}</div>
                <div data-question-id='92' data-tip={it.L('{JAPAN ONLY}TIP_92')} data-question-en='As the exercise deadline approaches, the price of an out-of-the-money binary option will move towards zero.'>{it.L('{JAPAN ONLY}As the exercise deadline approaches, the price of an out-of-the-money binary option will move towards zero.')}</div>
                <div data-question-id='93' data-tip={it.L('{JAPAN ONLY}TIP_93')} data-question-en='The price of a binary option is affected by not only the change in the underlying asset price, but also the change in remaining time to the exercise point.'>{it.L('{JAPAN ONLY}The price of a binary option is affected by not only the change in the underlying asset price, but also the change in remaining time to the exercise point.')}</div>
                <div data-question-id='94' data-tip={it.L('{JAPAN ONLY}TIP_94')} data-question-en='Implied volatility is a prediction of the future rate of change in the underlying asset.'>{it.L('{JAPAN ONLY}Implied volatility is a prediction of the future rate of change in the underlying asset.')}</div>
                <div data-question-id='95' data-tip={it.L('{JAPAN ONLY}TIP_95')} data-question-en='Historical volatility is a prediction of the future rate of change in the underlying asset.'>{it.L('{JAPAN ONLY}Historical volatility is a prediction of the future rate of change in the underlying asset.')}</div>
                <div data-question-id='96' data-tip={it.L('{JAPAN ONLY}TIP_96')} data-question-en='Delta refers to  a percentage change of the option price with respect to the change in the underlying asset price.'>{it.L('{JAPAN ONLY}Delta refers to  a percentage change of the option price with respect to the change in the underlying asset price.')}</div>
                <div data-question-id='97' data-tip={it.L('{JAPAN ONLY}TIP_97')} data-question-en='Option prices are normally dependant on elements such as the underlying asset price, the exercise price, the length of time until the exercise point, volatility, and interest rates. Apart from the fixed exercise price, all other elements are changing constantly, so an understanding of the relationships between each element and changes in the options price is necessary for the management of options trading risk.'>{it.L('{JAPAN ONLY}Option prices are normally dependant on elements such as the underlying asset price, the exercise price, the length of time until the exercise point, volatility, and interest rates. Apart from the fixed exercise price, all other elements are changing constantly, so an understanding of the relationships between each element and changes in the options price is necessary for the management of options trading risk.')}</div>
                <div data-question-id='98' data-tip={it.L('{JAPAN ONLY}TIP_98')} data-question-en='Option prices are normally dependant on elements such as the underlying asset price, the exercise price, the length of time until the exercise point, volatility, and interest rates. However, when the remaining time to the exercise point is very short, there is no need to consider these when managing option trading risk, as all these elements are constant.'>{it.L('{JAPAN ONLY}Option prices are normally dependant on elements such as the underlying asset price, the exercise price, the length of time until the exercise point, volatility, and interest rates. However, when the remaining time to the exercise point is very short, there is no need to consider these when managing option trading risk, as all these elements are constant.')}</div>
                <div data-question-id='99' data-tip={it.L('{JAPAN ONLY}TIP_99')} data-question-en='The Black-Scholes model is widely used to calculate theoretical option prices.'>{it.L('{JAPAN ONLY}The Black-Scholes model is widely used to calculate theoretical option prices.')}</div>
                <div data-question-id='100' data-tip={it.L('{JAPAN ONLY}TIP_100')} data-question-en='A modified version of the Black-Scholes model is widely used to calculate the theoretical prices of binary options.'>{it.L('{JAPAN ONLY}A modified version of the Black-Scholes model is widely used to calculate the theoretical prices of binary options.')}</div>
            </div>
        </div>
    </div>
);

export default KnowledgeTest;
