// This is an auto-generated list of strings used in js code for debugging purpose only
module.exports = [
    ' (account created)',
    ' (unavailable)',
    '1. This link was sent by you',
    '2. Your desktop window stays open',
    'AM',
    'Account',
    'Account Authenticated',
    'Account access is temporarily limited. Please check your inbox for more details.',
    'Account balance:',
    'Accounts List',
    'Acknowledge',
    'Action',
    'Add +/– to define a barrier offset. For example, +0.005 means a barrier that\'s 0.005 higher than the entry spot.',
    'Adjust trade parameters',
    'Admin',
    'Agree and accept',
    'All details must be clear — nothing blurry',
    'Allow camera access',
    'Amount',
    'Amount in',
    'An error occurred while loading the component',
    'Apply now as a professional investor',
    'Apr',
    'April',
    'Are you sure that you want to permanently delete the token',
    'Are you sure that you want to permanently revoke access to the application',
    'Are you sure you want to create a fiat account in [_1]?',
    'Are you sure you want to create your [_1] account now?',
    'Are you sure you want to deposit in [_1]?',
    'Are you sure?',
    'Asian Down',
    'Asian Up',
    'Asset',
    'Audit',
    'Audit Page',
    'Aug',
    'August',
    'Available Markets',
    'Average',
    'Back to trading',
    'Balance',
    'Barrier',
    'Barrier Change',
    'Bid',
    'Binance USD',
    'Binary Coin',
    'Bitcoin',
    'Blurry photo detected',
    'Browser',
    'Buy',
    'Buy price',
    'Call Spread',
    'Camera access is denied',
    'Camera not detected',
    'Camera not working',
    'Camera not working?',
    'Cancel',
    'Change Password',
    'Change currency',
    'Chart is not available for this underlying.',
    'Charting for this underlying is delayed',
    'Check back here to finish the submission',
    'Check selfie',
    'Check that it is connected and functional. You can also <fallback>continue verification on your phone</fallback>',
    'Check that your number is correct',
    'Check your image',
    'Check your mobile',
    'Checked',
    'Checking',
    'Choose document',
    'Click OK to proceed.',
    'Click here to open a Financial Account',
    'Click here to open a Gaming account',
    'Click here to open a Real Account',
    'Close',
    'Close Time',
    'Close identity verification screen',
    'Close-Low',
    'Closed Bid',
    'Closes',
    'Commodities',
    'Compressing Image',
    'Confirm',
    'Confirm changes',
    'Connected to your mobile',
    'Connecting to server',
    'Connection error: Please check your internet connection.',
    'Connection lost',
    'Continue',
    'Continue on phone',
    'Continue on your phone',
    'Continue trading',
    'Continue with the verification',
    'Contract',
    'Contract Confirmation',
    'Contract Details',
    'Contract Ends',
    'Contract Information',
    'Contract Result',
    'Contract Starts',
    'Contract Type',
    'Contract has not started yet',
    'Contract will be sold at the prevailing market price when the request is received by our servers. This price may differ from the indicated price.',
    'Copied',
    'Copy',
    'Copy link',
    'Copy the link to your mobile browser',
    'Copy the link to your phone',
    'Counterparty',
    'Country not found',
    'Country of Residence',
    'Create Account',
    'Create [_1] account',
    'Create account',
    'Credit/Debit',
    'Crypto',
    'Currency',
    'Current',
    'Current Time',
    'Current password',
    'Cut-off image detected',
    'Date',
    'Date and Time',
    'Deal Cancel. Fee',
    'Dec',
    'December',
    'Delete',
    'Demo Account',
    'Demo Accounts',
    'Demo Financial',
    'Demo Financial STP',
    'Demo Synthetic',
    'Deposit',
    'Deposits and withdrawals have been disabled on your account. Please check your email for more details.',
    'Description',
    'Details',
    'Digit',
    'Digit Differs',
    'Digit Even',
    'Digit Matches',
    'Digit Odd',
    'Digit Over',
    'Digit Under',
    'Disable',
    'Dismiss alert',
    'Do you want this to be a fiat account or crypto account? Please choose one:',
    'Do you wish to continue?',
    'Document example',
    'Document uploaded',
    'Documents from that country are not currently supported — <fallback>try another document type</fallback>',
    'Documents uploaded',
    'Documents you can use to verify your identity',
    'Does Not Touch',
    'Don\'t refresh this page',
    'Don\'t want to trade in [_1]? You can open another cryptocurrency account.',
    'Driver\'s license',
    'Driving licence',
    'Duration',
    'Email address',
    'Enable',
    'Enable camera',
    'End Time',
    'Ends Between',
    'Ends Outside',
    'Enlarge image',
    'Enter mobile number',
    'Enter your mobile number:',
    'Entry Spot',
    'Equals',
    'Ether Classic',
    'Ethereum',
    'Even/Odd',
    'Example of a blurry document',
    'Example of a cut-off document',
    'Example of a document with glare',
    'Exclude time cannot be for more than 5 years.',
    'Exclude time cannot be less than 6 months.',
    'Excluded from the website until',
    'Exit Spot',
    'Exit Spot Time',
    'Exit Time',
    'Expiry date is required for [_1].',
    'Face forward and make sure your eyes are clearly visible',
    'Face photo page',
    'Failed',
    'Feb',
    'February',
    'Fiat',
    'File ([_1]) size exceeds the permitted limit. Maximum allowed file size: [_2]',
    'File not uploaded.',
    'File size exceeded.',
    'File type not supported',
    'Final price',
    'Financial',
    'Financial Account',
    'Financial STP',
    'Finish',
    'First line of home address',
    'Follow these steps to recover camera access:',
    'Forex',
    'Fr',
    'Friday',
    'From account: ',
    'Front Side',
    'Front and back',
    'Gaming',
    'Gaming Account',
    'Get [_1]',
    'Get link via SMS',
    'Get secure link',
    'Get your secure link',
    'Glare detected',
    'Go back',
    'Go to statement',
    'Goes Outside',
    'Grant access to your camera from your browser settings',
    'Great, that\'s everything we need',
    'Guide',
    'Hence, your withdrawable balance is only up to [_1][_2], subject to your account’s available funds.',
    'Here\'s how to do it:',
    'High',
    'High Barrier',
    'High Tick',
    'High-Close',
    'High-Low',
    'Higher',
    'Higher or equal',
    'Higher/Lower',
    'Hint: it would take approximately [_1][_2] to crack your password.',
    'Hour',
    'How to scan a QR code',
    'I want to reapply',
    'ID number is required for [_1].',
    'IDK',
    'IP Address',
    'Identity card',
    'If it doesn’t work, download a QR code scanner from Google Play or the App Store',
    'In the EU, financial binary options are only available to professional investors.',
    'In/Out',
    'Indicates required field',
    'Indicative',
    'Insufficient balance.',
    'Invalid document format.',
    'Invalid email address.',
    'Invalid verification code.',
    'Investment',
    'It may be disconnected. <fallback>Try using your phone instead</fallback>.',
    'It may take a few minutes to arrive',
    'It must be an official photo ID',
    'It will only take a couple of minutes.',
    'It’ll take longer to verify you if we can’t read it',
    'Jan',
    'January',
    'Jul',
    'July',
    'Jun',
    'June',
    'Jurisdiction',
    'Keep this window open while using your mobile',
    'Last Login',
    'Last Used',
    'Linked to your computer',
    'Litecoin',
    'Loading',
    'Loading...',
    'Looks like you took too long',
    'Loss',
    'Low',
    'Low Barrier',
    'Low Tick',
    'Lower',
    'Lower or equal',
    'MT5',
    'MT5 withdrawals have been disabled on your account. Please check your email for more details.',
    'Make sure all of the document is in the photo',
    'Make sure details are clear to read, with no blur or glare',
    'Make sure everything is clear',
    'Make sure full document is visible',
    'Make sure your card details are clear to read, with no blur or glare',
    'Make sure your device has a working camera',
    'Make sure your device\'s camera works',
    'Make sure your license details are clear to read, with no blur or glare',
    'Make sure your passport details are clear to read, with no blur or glare',
    'Make sure your permit details are clear to read, with no blur or glare',
    'Make sure your selfie clearly shows your face',
    'Make sure§',
    'Mar',
    'March',
    'Matches/Differs',
    'Maximum multiplier of 1000.',
    'Maximum payout',
    'May',
    'Minimum of [_1] characters required.',
    'Minute',
    'Mo',
    'Monday',
    'More information can be found in an email sent to you.',
    'Move away from direct light',
    'Move away from direct light — no glare',
    'Multi-Collateral',
    'Multiple faces found',
    'Multiplier',
    'Multiplier Down',
    'Multiplier Up',
    'Must be under 10MB.',
    'Name',
    'Net profit',
    'Network status',
    'Never',
    'Never Used',
    'New password',
    'New token created.',
    'Next',
    'No authentication required',
    'No document detected',
    'No face found',
    'Not',
    'Not announced for this currency.',
    'Note',
    'Note:',
    'Note: You are limited to one fiat currency account. The currency of your fiat account can be changed before you deposit into your fiat account for the first time or create an MT5 account. You may also open one account for each supported cryptocurrency.',
    'Nov',
    'November',
    'Now',
    'Oct',
    'October',
    'Offline',
    'Once you\'ve finished we\'ll take you to the next step',
    'Online',
    'Only Downs',
    'Only Ups',
    'Only Ups/Only Downs',
    'Only [_1] are allowed.',
    'Only letters, numbers, space, and hyphen are allowed.',
    'Only letters, numbers, space, and these special characters are allowed: [_1]',
    'Only letters, numbers, space, hyphen, period, and apostrophe are allowed.',
    'Only letters, numbers, space, hyphen, period, comma, and apostrophe are allowed.',
    'Only letters, numbers, space, underscore, and hyphen are allowed for ID number ([_1]).',
    'Only letters, space, hyphen, period, and apostrophe are allowed.',
    'Only your face can be in the selfie',
    'Open a Financial Account',
    'Open a Real Account',
    'Open the link and complete the tasks',
    'Open the link on your mobile',
    'Open your new bank account',
    'Opens',
    'Over/Under',
    'PM',
    'Passport',
    'Passport photo page',
    'Password is not strong enough.',
    'Password should have lower and uppercase English letters with numbers.',
    'Paxos Standard',
    'Payment Agent services are not available in your country or in your preferred currency.',
    'Payments',
    'Payout',
    'Payout Range',
    'Pending',
    'Percentage',
    'Permissions',
    'Photo of your document',
    'Photo of your face',
    'Place of birth',
    'Please [_1]accept the updated Terms and Conditions[_2] to lift your deposit and trading limits.',
    'Please [_1]accept the updated Terms and Conditions[_2].',
    'Please [_1]complete your account profile[_2] to lift your withdrawal and trading limits.',
    'Please [_1]deposit[_2] to your account.',
    'Please [_1]log in[_2] or [_3]sign up[_4] to view this page.',
    'Please accept the terms and conditions.',
    'Please check your email for further instructions.',
    'Please check your email for the password reset link.',
    'Please choose a currency',
    'Please complete the [_1]Real Account form[_2] to verify your age as required by the [_3]UK Gambling[_4] Commission (UKGC).',
    'Please complete the [_1]financial assessment form[_2] to lift your withdrawal and trading limits.',
    'Please complete your [_1]personal details[_2] before you proceed.',
    'Please confirm that all the information above is true and complete.',
    'Please confirm that you are not a politically exposed person.',
    'Please ensure that you have the Telegram app installed on your device.',
    'Please enter a valid Login ID.',
    'Please enter a valid phone number, including the country code (e.g. +15417541234).',
    'Please note that the selected currency is allowed for limited accounts only.',
    'Please reapply once the required criteria has been fulfilled.',
    'Please reload the page',
    'Please select',
    'Please select a country',
    'Please select a reason.',
    'Please select a valid time.',
    'Please select at least one scope',
    'Please select the checkbox.',
    'Please select the currency for this account:',
    'Please set [_1]country of residence[_2] before upgrading to a real-money account.',
    'Please set the [_1]currency[_2] of your account.',
    'Please set your [_1]30-day turnover limit[_2] to remove deposit limits.',
    'Please specify the reasons for closing your accounts',
    'Please submit your [_1]proof of address[_2].',
    'Please submit your [_1]proof of identity and proof of address[_2].',
    'Please submit your [_1]proof of identity[_2].',
    'Please try again',
    'Point your phone’s camera at the QR code',
    'Postal Code/ZIP',
    'Potential Payout',
    'Potential Profit',
    'Potential Profit/Loss',
    'Predict the direction<br />and purchase',
    'Previous',
    'Profit',
    'Profit/Loss',
    'Provide the whole document page for best results',
    'Purchase',
    'Purchase Price',
    'Purchase Time',
    'Purchase request sent',
    'Put Spread',
    'Read',
    'Real',
    'Real Account',
    'Real Financial',
    'Real Financial STP',
    'Real Synthetic',
    'Real-Money Account',
    'Real-Money Accounts',
    'Recover camera access to continue face verification',
    'Recovery',
    'Redo',
    'Ref.',
    'Reference ID',
    'Refresh',
    'Refresh this page to restart the identity verification process',
    'Remaining Time',
    'Remember to press stop when you\'re done. <fallback>Redo video actions</fallback>',
    'Remove your glasses, if necessary',
    'Resale not offered',
    'Resend link',
    'Reset Barrier',
    'Reset Call',
    'Reset Password',
    'Reset Put',
    'Reset Time',
    'Reset the balance of your virtual account to [_1] anytime.',
    'Residence permit',
    'Restart process on a different device',
    'Restart the process on the latest version of Google Chrome',
    'Restart the process on the latest version of Safari',
    'Return',
    'Reverse Side',
    'Revoke access',
    'Rise/Fall',
    'STASIS Euro',
    'Sa',
    'Sale Date',
    'Sale Price',
    'Saturday',
    'Scan QR code',
    'Scan the QR code with your phone',
    'Scans and photocopies are not accepted',
    'Scopes',
    'Search for country',
    'Search...',
    'Select Asset',
    'Select Trade Type',
    'Select a %{country} document',
    'Select country',
    'Select date',
    'Select issuing country',
    'Select payment agent',
    'Select your market and underlying asset',
    'Select your trade type',
    'Selected Tick',
    'Selfie',
    'Selfie uploaded',
    'Sell',
    'Sell at market',
    'Send a secure link to your phone',
    'Send link',
    'Send this one-time link to your phone',
    'Sending',
    'Sep',
    'September',
    'Session duration limit cannot be more than 6 weeks.',
    'Set currency',
    'Settles',
    'Should be [_1]',
    'Should be a valid number.',
    'Should be between [_1] and [_2]',
    'Should be less than [_1]',
    'Should be more than [_1]',
    'Should start with letter or number, and may contain hyphen and underscore.',
    'Show all details — including the bottom 2 lines',
    'Sign out',
    'Sign up',
    'Something\'s gone wrong',
    'Sorry, account signup is not available in your country.',
    'Sorry, an error occurred while processing your account.',
    'Sorry, an error occurred while processing your request.',
    'Sorry, but binary options trading is not available in your financial account.',
    'Sorry, deposits for this currency are currently disabled.',
    'Sorry, no mobile phone bills',
    'Sorry, this feature is available to virtual accounts only.',
    'Sorry, this feature is not available in your jurisdiction.',
    'Sorry, withdrawals for this currency are currently disabled.',
    'Spot',
    'Spot Time',
    'Spot Time (GMT)',
    'Stake',
    'Start Time',
    'State/Province',
    'Status',
    'Stays Between',
    'Step',
    'Steps required to continue verification on your mobile',
    'Stock Indices',
    'Stocks',
    'Su',
    'Submit document',
    'Submit identity card (back)',
    'Submit identity card (front)',
    'Submit license (back)',
    'Submit license (front)',
    'Submit passport photo page',
    'Submit residence permit (back)',
    'Submit residence permit (front)',
    'Submit verification',
    'Submitted',
    'Submitting',
    'Successful',
    'Sunday',
    'Synthetic',
    'Synthetic Indices',
    'Take a photo',
    'Take a photo of the back of your card',
    'Take a photo of the back of your license',
    'Take a photo of the front of your card',
    'Take a photo of the front of your license',
    'Take a photo of your passport photo page',
    'Take a photo using the <fallback>basic camera mode</fallback> instead',
    'Take a photo with your phone',
    'Take a selfie',
    'Take a selfie showing your face',
    'Take photo',
    'Target',
    'Telephone',
    'Tether ERC20',
    'Tether ERC20 (eUSDT) is a version of Tether that\'s pegged to USD and is hosted on the Ethereum platform.',
    'Tether Omni',
    'Tether Omni (USDT) is a version of Tether that\'s pegged to USD and is built on the Bitcoin blockchain.',
    'Th',
    'Thank you',
    'Thank you for signing up! Please check your email to complete the registration process.',
    'Thank you, we\'ll get back to you within 24 hours',
    'The [_1] password of account number [_2] has been changed.',
    'The email address provided is already in use. If you forgot your password, please try our <a href="[_1]">password recovery tool</a> or contact our customer service.',
    'The link only works on mobile devices',
    'The maximum number of tokens ([_1]) has been reached.',
    'The photo should clearly show your document',
    'The reason should be between 5 and 250 characters',
    'The reset time is [_1]',
    'The server <a href="[_1]">endpoint</a> is: [_2]',
    'The two passwords that you entered do not match.',
    'There was an error',
    'There was some invalid character in an input field.',
    'These are the documents most likely to show your current home address',
    'This account is disabled',
    'This account is excluded until [_1]',
    'This contract is only available on DTrader.[_1][_2]Go to Dtrader[_3] to close or cancel this contract.',
    'This contract is only available on [_1]DTrader[_2].',
    'This contract lost',
    'This contract won',
    'This feature is not relevant to virtual-money accounts.',
    'This field is required.',
    'This is a staging server - For testing purposes only',
    'This is your [_1] account.',
    'This page is only available to logged out clients.',
    'Thursday',
    'Tick',
    'Ticks history returned an empty array.',
    'Time is in the wrong format.',
    'Time out cannot be in the past.',
    'Time out cannot be more than 6 weeks.',
    'Time out must be after today.',
    'Timed out until',
    'Tips',
    'Tips to take a good selfie',
    'To account: ',
    'To open a bank account, we will need to verify your identity.',
    'To smoothly verify you, we need a better photo',
    'Today',
    'Token',
    'Too many failed attempts',
    'Top up error',
    'Top-up successful',
    'Total Cost',
    'Total Profit/Loss',
    'Touches',
    'Town/City',
    'Trade',
    'Trading Information',
    'Trading and withdrawals have been disabled on your account. Kindly [_1]contact customer support[_2] for assistance.',
    'Trading contracts for difference (CFDs) on Synthetic Indices may not be suitable for everyone. Please ensure that you fully understand the risks involved, including the possibility of losing all the funds in your MT5 account. Gambling can be addictive – please play responsibly.',
    'Trading is unavailable at this time.',
    'Transaction ID',
    'Transaction performed by [_1] (App ID: [_2])',
    'True USD',
    'Try our [_1]Synthetic Indices[_2].',
    'Try our other markets.',
    'Try using a JPG or PNG file',
    'Try using another file type.',
    'Tu',
    'Tuesday',
    'Type',
    'USD Coin',
    'USDK',
    'Unable to read file [_1]',
    'Understood',
    'Unknown OS',
    'Unsupported browser',
    'Up to [_1] decimal places are allowed.',
    'Up/Down',
    'Upcoming Events',
    'Upgrade now',
    'Upload',
    'Upload a selfie from your computer',
    'Upload anyway',
    'Upload back of card from your computer',
    'Upload back of license from your computer',
    'Upload front of card from your computer',
    'Upload front of license from your computer',
    'Upload passport photo page',
    'Upload passport photo page from your computer',
    'Upload photo',
    'Uploads successful',
    'Verification code is wrong. Please use the link sent to your email.',
    'Verification complete',
    'Verification required',
    'Verify Identity',
    'Verify Reset Password',
    'Verify identity',
    'View',
    'View chart',
    'View from camera',
    'Virtual',
    'Waiting for contract settlement.',
    'Waiting for entry tick.',
    'Waiting for exit tick.',
    'We',
    'We cannot verify you without using your camera',
    'We\'ll compare it with your document',
    'We\'re now ready to verify your identity',
    'We\'ve sent a secure link to %{number}',
    'Wednesday',
    'We’ll update your limits. Click [_1]Agree and accept[_2] to acknowledge that you are fully responsible for your actions, and we are not liable for any addiction or loss.',
    'When prompted, you must enable camera access to continue',
    'When you click "OK" you will be excluded from trading on the site until the selected date.',
    'Withdraw',
    'Withdrawals have been disabled on your account. Please check your email for more details.',
    'Withdrawals have been disabled on your account. Please wait until your uploaded documents are verified.',
    'Yes',
    'Yes I\'m sure',
    'Yes, I\'m sure',
    'You are categorised as a professional client.',
    'You are categorised as a retail client. Apply to be treated as a professional trader.',
    'You are limited to one fiat account. You can change the currency of your fiat account anytime before you make a first-time deposit or create an MT5 account.',
    'You can [_1]set a new currency[_2] before you deposit for the first time or create an MT5 account.',
    'You can close this window without interrupting your trade.',
    'You can no longer change the currency because you\'ve created an MT5 account.',
    'You can no longer change the currency because you\'ve made a first-time deposit.',
    'You can now return to your computer to continue',
    'You can top up your demo account with an additional [_1] if your balance is [_2] or less.',
    'You did not change anything.',
    'You do not need to authenticate your account at this time.[_1]We will inform you when your account needs to be authenticated.',
    'You have already withdrawn [_1][_2] in aggregate over the last [_3] days.',
    'You have already withdrawn [_1][_2].',
    'You have insufficient funds in your Binary account, please <a href="[_1]">add funds</a>.',
    'You have insufficient funds in your MT5 account.',
    'You have not granted access to any applications.',
    'You have reached the rate limit of requests per second. Please try later.',
    'You have reached the withdrawal limit.',
    'You have sold this contract at [_1] [_2]',
    'You have successfully changed your account currency from [_1] to [_2].',
    'You have successfully disabled two-factor authentication for your account.',
    'You have successfully enabled two-factor authentication for your account.',
    'You have successfully set your account currency to [_1].',
    'You may open one account for each supported cryptocurrency.',
    'You should enter [_1] characters.',
    'You will be redirected to a third-party website which is not owned by Binary.com.',
    'You will not be able to change your fiat account\'s currency after creating this MT5 account. Are you sure you want to proceed?',
    'You will not be able to change your fiat account\'s currency after making this deposit. Are you sure you want to proceed?',
    'You\'ll need to restart your verification on your computer',
    'Your [_1] day withdrawal limit is currently [_2][_3].',
    'Your [_1]proof of address[_2] has expired.',
    'Your [_1]proof of address[_2] has not been verified.',
    'Your [_1]proof of identity[_2] has expired.',
    'Your [_1]proof of identity[_2] has not been verified.',
    'Your [_1]proof of identity[_3] and [_2]proof of address[_3] have expired.',
    'Your [_1]proof of identity[_3] and [_2]proof of address[_3] have not been verified.',
    'Your account has no Login/Logout activity.',
    'Your account has no trading activity.',
    'Your account is fully authenticated and your withdrawal limits have been lifted.',
    'Your account is restricted. Kindly [_1]contact customer support[_2] for assistance.',
    'Your application to be treated as a professional client is being processed.',
    'Your cashier is locked.',
    'Your changes have been updated successfully.',
    'Your changes have been updated.',
    'Your computer may take a few seconds to update',
    'Your demo account balance is currently [_1] or less. You may top up your account with an additional [_2].',
    'Your face is needed in the selfie',
    'Your fiat account\'s currency is currently set to [_1].',
    'Your fiat account\'s currency is set to [_1].',
    'Your link will expire in one hour',
    'Your mobile link will expire in one hour',
    'Your password cannot be the same as your email address.',
    'Your password has been successfully reset. Please log into your account using your new password.',
    'Your password is one of the most commonly used passwords on the internet. Please choose a unique password.',
    'Your professional client request is [_1]not approved[_2].',
    'Your request to transfer [_1] [_2] from [_3] to [_4] has been successfully processed.',
    'Your request to withdraw [_1] [_2] from your account [_3] to Payment Agent [_4] account has been successfully processed.',
    'Your session duration limit will end in [_1] seconds.',
    'Your settings have been updated successfully.',
    'Your token has expired or is invalid. Please click <a href="[_1]">here</a> to restart the verification process.',
    'Your token has expired or is invalid. Please click [_1]here[_2] to restart the verification process.',
    'Your trading statistics since [_1].',
    'Your transaction reference is',
    'Your transaction reference number is [_1]',
    'Your web browser ([_1]) is out of date and may affect your trading experience. Proceed at your own risk. [_2]Update browser[_3]',
    'Your withdrawal limit is [_1][_2].',
    '[_1] Account',
    '[_1] Account [_2]',
    '[_1] Please click the link below to restart the password recovery process.',
    '[_1] and [_2] cannot be the same.',
    '[_1] days [_2] hours [_3] minutes',
    '[_1] deposit from [_2] to account number [_3] is done. Transaction ID: [_4]',
    '[_1] has been credited into your MT5 Demo Account: [_2].',
    '[_1] has been credited into your Virtual Account: [_2].',
    '[_1] requires your browser\'s web storage to be enabled in order to function properly. Please enable it or exit private browsing mode.',
    '[_1] withdrawal from account number [_2] to [_3] is done. Transaction ID: [_4]',
    '[_1]Manage your accounts[_2]',
    '[_1]No, change my fiat account\'s currency now[_2]',
    'account',
    'accounts',
    'back',
    'close',
    'day',
    'days',
    'details',
    'e.g. United States',
    'for account [_1]',
    'hour',
    'hours',
    'including Deal Cancel. Fee',
    'letters',
    'million',
    'minute',
    'minutes',
    'numbers',
    'or',
    'or upload photo – no scans or photocopies',
    'second',
    'seconds',
    'space',
    'thousand',
    'tick',
    'ticks',
    'years',
    '{SPAIN ONLY}However, Binary Investments (Europe) Ltd has assessed your knowledge and experience and deems the product appropriate for you.',
    '{SPAIN ONLY}This is a product with leverage. You should be aware that losses may be higher than the amount initially paid to purchase the product.',
    '{SPAIN ONLY}You are about to purchase a product that is not simple and may be difficult to understand: Contracts for difference and forex. As a general rule, the CNMV considers that such products are not appropriate for retail clients, due to their complexity.',
];
