import React from 'react';

const CodeOfConduct = () => (
    <div>
        <h2 data-anchor='code-of-conduct'>{it.L('Code of Conduct for Business Partners')}</h2>
        <h2 data-anchor='introduction'>{it.L('Introduction')}</h2>
        <p>{it.L('[_1] is one of the oldest and most successful online trading companies in the world. Our commitment to high standards of ethics is one of the key factors that will ensure our continuing success.  Our Business Principles summarise the values that underpin our work.', it.website_name)}</p>
        <p>{it.L('We expect our business partners as well as our employees to abide by these same values. This Code explains how the Business Principles apply to you. It is intended to provide you with a clear and straightforward summary of the main points. You should read it together with the Payment Agent Terms and Conditions, the Affiliate Programme Terms and Conditions, and the more detailed policies and product descriptions, that appear on our website.')}</p>
        <p>{it.L('Each section starts with a paragraph from the Business Principles written in italics. We then explain how this paragraph applies to business partners.')}</p>
        <p>{it.L('Our business is founded on collaboration and we aim to build long-term, mutually beneficial relationships with our partners. However, we will never compromise our commitment to business integrity. In cases where our partners are unwilling or unable to abide by our principles, we reserve the right to withdraw from the business relationship.')}</p>
        <p>{it.L('If you wish to seek guidance on any aspect these Business Principles, you should contact [_1]compliance@binary.com[_2]', '<a href="mailto:compliance@binary.com">', '</a>')}</p>
        <h2 data-anchor='legal-and-regulatory-compliance'>{it.L('Legal and regulatory compliance')}</h2>
        <p>{it.L('We hold multiple licenses to comply with regulations around the world. [_1] abides by all applicable laws and regulations in the countries where it operates.', it.website_name)}</p>
        <p>{it.L('The Regulatory Information section of our website gives more details according to the geographical location of our holding company and its various subsidiaries.  Business partners are responsible for ensuring that they comply with the applicable laws, rules, and regulations in the countries where they themselves operate. For example, these include laws relating to advertising, data protection, privacy, and social responsibility.')}</p>
        <h2 data-anchor='responsible-trading'>{it.L('Responsible trading')}</h2>
        <p>{it.L('We describe the risks as well as the potential rewards that apply to our services.  We emphasise that clients must have a clear understanding of those risks. Recognising that trading can be addictive, we emphasise that clients must trade only with money that they can afford to lose, and they must never trade with borrowed funds. They should put a limit on their winnings, and they should never trade when they are tired or under the influence of alcohol or medication.')}</p>
        <p>{it.L('Affiliates have a particular responsibility to explain our services clearly and accurately. Of course, we want our clients to share the excitement of trading. However, they need to understand clearly that they may win as well as lose. It is essential to avoid exaggerated descriptions of potential winnings.')}</p>
        <p>{it.L('Affiliates are required to display a risk warning on their website and associated materials, with wording such as the following:')}</p>
        <p>{it.L('The products offered on the [_1] website include binary options, contracts for difference ("CFDs") and other complex derivatives. Trading binary options may not be suitable for everyone. Trading CFDs carries a high level of risk since leverage can work both to your advantage and disadvantage. As a result, the products offered on the website may not be suitable for all investors because of the risk of losing all of your invested capital. You should never invest money that you cannot afford to lose, and never trade with borrowed money. Before trading in the complex products offered, please be sure to understand the risks involved.', it.website_name)}</p>
        <h2 data-anchor='transparency'>{it.L('Transparency')}</h2>
        <p>{it.L('Recognising the complexities of the financial markets, we describe our trading options fairly and in detail. We include accurate product descriptions on our website, as well as free webinars. We offer clients the opportunity to set up virtual accounts in order to experiment with the system free of charge. We encourage our clients to study all these sources of information carefully before they trade.')}</p>
        <p>{it.L('This is a continuation of the same point. [_1] offers clients a variety of ways of learning how to trade responsibly. Affiliates should make sure that they do learn, for example by encouraging them to build up their expertise with a virtual account rather than trading with real funds straightaway.', it.website_name)}</p>
        <h2 data-anchor='reliability'>{it.L('Reliability')}</h2>
        <p>{it.L('We keep our promises. When clients trade on our system, we clearly define what they may win, what they may lose, and in what circumstances. If they win, we pay out their rewards quickly and efficiently.')}</p>
        <p>{it.L('This is one of our core commitments to clients.')}</p>
        <h2 data-anchor='confidentiality'>{it.L('Confidentiality')}</h2>
        <p>{it.L('We will not disclose any confidential information that comes into our possession through our client relationships unless required to do so by a regulator or law enforcement authority.')}</p>
        <p>{it.L('A regulator or law enforcement authority might ask us to share otherwise confidential information in connection with investigations into a suspected criminal offence, particularly money-laundering (see below). If you receive a request to share confidential information, you should immediately inform [_1]compliance@binary.com[_2] who will give guidance on how to respond.', '<a href="mailto:compliance@binary.com">', '</a>')}</p>
        <h2 data-anchor='no-bribery'>{it.L('No bribery')}</h2>
        <p>{it.L('We do not pay bribes in any form, and we do not permit anyone else to pay bribes on our behalf. This includes an absolute prohibition on bribes to government officials as well as people in positions of responsibility in the private sector.')}</p>
        <p>{it.L('We recognise that bribes may take the form of gifts in kind as well as financial payments. We will not offer or accept gifts that could affect either side’s impartiality, influence a business decision or lead to the improper performance of an official duty.')}</p>
        <p>{it.L('[_1]’s refusal to pay bribes is an essential part of our ethical commitment. Similarly, we do not permit our business partners to pay bribes when acting on our behalf.', it.website_name)}</p>
        <h2 data-anchor='anti-money-laundering'>{it.L('Anti-money laundering')}</h2>
        <p>{it.L('We will not permit our products or payment facilities to be used to facilitate money laundering, terrorist financing, or other criminal activities. Where appropriate, we will conduct Know Your Customer (KYC) checks on our clients. We will report suspicious transactions to relevant authorities.')}</p>
        <p>{it.L('Clients may trade on our platforms only when they are using their own money and are drawing on funds that have been acquired honestly. If you have any suspicion that clients are using money that has been acquired dishonestly, you must inform [_1].  In such cases, we may decide to conduct checks on the client’s status and background. [_2] management will decide what information needs to be reported to government officials and through what channels.', '<a href="mailto:compliance@binary.com">compliance@binary.com</a>', it.website_name)}</p>
        <h2 data-anchor='no-insider-trading'>{it.L('No insider trading')}</h2>
        <p>{it.L('We prohibit all forms of insider trading. This means that clients are not permitted to trade on the basis of knowledge that is not publicly available. For example, such knowledge may include confidential information gained through their work. ')}</p>
        <p>{it.L('Special conditions apply to clients who are employed in the banking and/or finance sector. They may not conduct trades through our website without the knowledge of their employer. They must check that any such trading is in accordance with their employer\'s policies.')}</p>
        <p>{it.L('You must ensure that potential clients are aware of the prohibition on insider trading based on confidential information. If you have any suspicion that such trading is taking place you must inform [_1]compliance@binary.com[_2].',  '<a href="mailto:compliance@binary.com">', '</a>')}</p>
        <h2 data-anchor='fair-competition'>{it.L('Fair Competition')}</h2>
        <p>{it.L('[_1] prohibits anti-competitive agreements or conduct, including fixing prices, restricting the supply of services, price rigging and market sharing. We require our business partners to commit to free and fair competition and to abide by relevant competition laws and regulations.', it.website_name)}</p>
        <p>{it.L('Again, this means that you must not share sensitive commercial information with [_1]’s competitors, nor with your own competitors.', it.website_name)}</p>
        <h2 data-anchor='conflicts-of-interest'>{it.L('Conflicts of interest')}</h2>
        <p>{it.L('[_1] employees and affiliates must avoid conflicts of interest. For example, they may not compete with the company, either directly or indirectly, or use knowledge gained while working for [_1] to help anyone else compete with it.', it.website_name)}</p>
        <p>{it.L('If an actual or potential conflict appears in the course of your work, they must declare it to [_1]compliance@binary.com[_2]', '<a href="mailto:compliance@binary.com">', '</a>')}</p>
        <h2 data-anchor='books-and-records'>{it.L('Books and records')}</h2>
        <p>{it.L('We take care to maintain accurate books and records that reflect our business transactions as they occur, and we keep them for as long as legally required. ')}</p>
        <p>{it.L('You must ensure that you fill in all records accurately and in as much detail as required.')}</p>
    </div>
);

export default CodeOfConduct;
