export const contract_type_display = {
    ASIANU      : 'Asian Up',
    ASIAND      : 'Asian Down',
    CALL        : 'Higher',
    CALLE       : 'Higher or equal',
    PUT         : 'Lower',
    DIGITMATCH  : 'Digit Matches',
    DIGITDIFF   : 'Digit Differs',
    DIGITODD    : 'Digit Odd',
    DIGITEVEN   : 'Digit Even',
    DIGITOVER   : 'Digit Over',
    DIGITUNDER  : 'Digit Under',
    EXPIRYMISS  : 'Ends Outside',
    EXPIRYRANGE : 'Ends Between',
    EXPIRYRANGEE: 'Ends Between',
    LBFLOATCALL : 'Close-Low',
    LBFLOATPUT  : 'High-Close',
    LBHIGHLOW   : 'High-Low',
    RANGE       : 'Stays Between',
    UPORDOWN    : 'Goes Outside',
    ONETOUCH    : 'Touches',
    NOTOUCH     : 'Does Not Touch',
};
