var texts_json  = require('../../autogenerated/texts').texts_json;
var template    = require('./utility').template;
var moment      = require('moment');

var Localize = (function () {
    var texts = {},
        localizedTexts;
    var init = function () {
        // make texts objects localizable
        Object.keys(texts_json).forEach(function(key) {
            texts[key] = texts_json[key] ? texts_json[key] : {};
        });
    };

    var localizeForLang = function(lang) {
        init();
        localizedTexts = texts[lang];
        moment.locale(lang.toLowerCase());
    };

    var do_localize = function(text, params) {
        var index = text.replace(/[\s|.]/g, '_');
        text = localizedTexts[index] || text;
        // only do templating when explicitly required
        return params ? template(text, params) : text;
    };

    var localize = function (text, params) {
        if (Array.isArray(text)) {
            return text.map(function(t) { return do_localize(t, params); });
        }
        // else
        return do_localize(text, params);
    };

    return {
        localizeForLang: localizeForLang,
        localize       : localize,
    };
})();

module.exports = {
    localize       : Localize.localize,
    localizeForLang: Localize.localizeForLang,
};
