import React from 'react';

const TwoFactorAuthentication = () => (
    <React.Fragment>
        <h1>Two-Factor Authentication</h1>
        <p>{it.L('Protect your account with two-factor authentication. Each time you sign into your account, you will need to enter your password, plus an authentication code generated by an app on your smartphone.')}</p>

        <div id='should_enable' className='invisible'>
            <div>
                <p>{it.L('Two-factor authentication is currently disabled.')}</p>
            </div>

            <h2>{it.L('How to setup two-factor authentication for your [_1] account', it.website_name)}</h2>

            <div className='steps'>
                <div className='step'>
                    <div className='border-bottom' />
                    <div className='circle'>1</div>
                    <div className='center-text'>
                        {/* <img src='http://placehold.it/50x50' /> */}
                    </div>
                    <p>{it.L('Scan the QR code below with your authentication app (such as Google Authenticator, Authy, and Duo Mobile)')}</p>
                    <p>QR code here</p>
                </div>
                <div className='step'>
                    <div className='border-bottom' />
                    <div className='circle'>2</div>
                    <div className='center-text'>
                        {/* <img src='http://placehold.it/50x50' /> */}
                    </div>
                    <p>{it.L('Enter the authentication code generated by the app below')}</p>
                </div>
            </div>
        </div>

        <div id='should_disable' className='invisible'>
            <div>
                <p>{it.L('Two-factor authentication is currently enabled.')}</p>
            </div>
        </div>

        <form id='frm_two_factor_auth'>
            <div className='gr-padding-10'>
                <input autoComplete='off' name='otp' id='otp' />
            </div>
            <button className='button-secondary' type='submit'>
                {it.L('Enable')}
            </button>
        </form>
    </React.Fragment>
);

export default TwoFactorAuthentication;
