var config = require('./config');
var pjax = require('./binary/base/pjax');

require('./binary/static_pages/endpoint');
var logged_in = require('./binary/base/logged_in');
var login = require('./binary/base/login');
var markets = require('./binary/base/markets');
var menu_content = require('./binary/base/menu_content');
var onerror = require('./binary/base/onerror');
var page = require('./binary/base/page');
var storage = require('./binary/base/storage');
var utility = require('./binary/base/utility');
var base = require('./binary/base');
var active_symbols = require('./binary/common_functions/active_symbols');
var button = require('./binary/common_functions/attach_dom/button');
var flextable = require('./binary/common_functions/attach_dom/flextable');
var password_strength_meter = require('./binary/common_functions/attach_dom/password_strength_meter');
var table = require('./binary/common_functions/attach_dom/table');
var common_data = require('./binary/common_functions/common_data');
// var compatibility = require('./binary/common_functions/compatibility');
var currency_to_symbol = require('./binary/common_functions/currency_to_symbol');
var event_handler = require('./binary/common_functions/event_handler');
var frontend = require('./binary/common_functions/frontend');
var get_app_details = require('./binary/common_functions/get_app_details');
var guide = require('./binary/common_functions/guide');
var passwordmeter = require('./binary/common_functions/passwordmeter');
var risk_classification = require('./binary/common_functions/risk_classification');
var session_duration_limit = require('./binary/common_functions/session_duration_limit');
var string_util = require('./binary/common_functions/string_util');
var traffic_source = require('./binary/common_functions/traffic_source');
var valid_account_opening = require('./binary/common_functions/valid_account_opening');
var validation = require('./binary/common_functions/validation');
var validation_v2 = require('./binary/common_functions/validation_v2');
var selected_dates = require('./binary/components/date_picker/selected_dates');
var date_picker = require('./binary/components/date_picker');
var time_picker = require('./binary/components/time_picker');
var trackjs_onerror = require('./binary/components/trackjs_onerror');
var get_started_jp = require('./binary/static_pages/get_started_jp');
var job_details = require('./binary/static_pages/job_details');
var static_pjax = require('./binary/static_pages/static_pjax');
var validator = require('./binary/validator');
var account_transferws = require('./binary/websocket_pages/cashier/account_transferws');
var cashier = require('./binary/websocket_pages/cashier/cashier');
var deposit_withdraw_ws = require('./binary/websocket_pages/cashier/deposit_withdraw_ws');
var payment_agent_listws = require('./binary/websocket_pages/cashier/payment_agent_listws');
var payment_agent_withdrawws = require('./binary/websocket_pages/cashier/payment_agent_withdrawws');
var asset_indexws_data = require('./binary/websocket_pages/resources/asset_index/asset_indexws.data');
var asset_indexws_ui = require('./binary/websocket_pages/resources/asset_index/asset_indexws.ui');
var asset_indexws = require('./binary/websocket_pages/resources/asset_indexws');
var market_timesws_data = require('./binary/websocket_pages/resources/market_times/market_timesws.data');
var market_timesws_ui = require('./binary/websocket_pages/resources/market_times/market_timesws.ui');
var market_timesws = require('./binary/websocket_pages/resources/market_timesws');
var socket = require('./binary/websocket_pages/socket');
var analysis = require('./binary/websocket_pages/trade/analysis');
var barriers = require('./binary/websocket_pages/trade/barriers');
var digit_infows = require('./binary/websocket_pages/trade/charts/digit_infows');
var highchartws = require('./binary/websocket_pages/trade/charts/highchartws');
var common = require('./binary/websocket_pages/trade/common');
var content = require('./binary/websocket_pages/trade/content');
var contract = require('./binary/websocket_pages/trade/contract');
var currency = require('./binary/websocket_pages/trade/currency');
var defaults = require('./binary/websocket_pages/trade/defaults');
var duration = require('./binary/websocket_pages/trade/duration');
var event_ = require('./binary/websocket_pages/trade/event');
var message = require('./binary/websocket_pages/trade/message');
var price = require('./binary/websocket_pages/trade/price');
var process_ = require('./binary/websocket_pages/trade/process');
var purchase = require('./binary/websocket_pages/trade/purchase');
var starttime = require('./binary/websocket_pages/trade/starttime');
var symbols = require('./binary/websocket_pages/trade/symbols');
var tick = require('./binary/websocket_pages/trade/tick');
var tick_trade = require('./binary/websocket_pages/trade/tick_trade');
var tradepage = require('./binary/websocket_pages/trade/tradepage');
var authenticate = require('./binary/websocket_pages/user/account/authenticate');
var change_password = require('./binary/websocket_pages/user/account/change_password');
var payment_agent_transfer_data = require('./binary/websocket_pages/user/account/payment_agent_transfer/payment_agent_transfer.data');
var payment_agent_transfer_init = require('./binary/websocket_pages/user/account/payment_agent_transfer/payment_agent_transfer.init');
var payment_agent_transfer_ui = require('./binary/websocket_pages/user/account/payment_agent_transfer/payment_agent_transfer.ui');
var payment_agent_transfer = require('./binary/websocket_pages/user/account/payment_agent_transfer');
var portfolio_init = require('./binary/websocket_pages/user/account/portfolio/portfolio.init');
var portfolio = require('./binary/websocket_pages/user/account/portfolio');
var profits_table_data = require('./binary/websocket_pages/user/account/profit_table/profit_table.data');
var profit_table_init = require('./binary/websocket_pages/user/account/profit_table/profit_table.init');
var profit_table_ui = require('./binary/websocket_pages/user/account/profit_table/profit_table.ui');
var profit_table = require('./binary/websocket_pages/user/account/profit_table');
var api_token = require('./binary/websocket_pages/user/account/settings/api_token');
var authorised_apps_data = require('./binary/websocket_pages/user/account/settings/authorised_apps/authorised_apps.data');
var authorised_apps_init = require('./binary/websocket_pages/user/account/settings/authorised_apps/authorised_apps.init');
var authorised_apps_ui = require('./binary/websocket_pages/user/account/settings/authorised_apps/authorised_apps.ui');
var authorised_apps = require('./binary/websocket_pages/user/account/settings/authorised_apps');
var financial_assessment = require('./binary/websocket_pages/user/account/settings/financial_assessment');
var iphistory_data = require('./binary/websocket_pages/user/account/settings/iphistory/iphistory.data');
var iphistory_init = require('./binary/websocket_pages/user/account/settings/iphistory/iphistory.init');
var iphistory_ui = require('./binary/websocket_pages/user/account/settings/iphistory/iphistory.ui');
var iphistory = require('./binary/websocket_pages/user/account/settings/iphistory');
var limits_init = require('./binary/websocket_pages/user/account/settings/limits/limits.init');
var limits_ui = require('./binary/websocket_pages/user/account/settings/limits/limits.ui');
var limits = require('./binary/websocket_pages/user/account/settings/limits');
var metatrader_data = require('./binary/websocket_pages/user/account/settings/metatrader/metatrader.data');
var metatrader_ui = require('./binary/websocket_pages/user/account/settings/metatrader/metatrader.ui');
var metatrader = require('./binary/websocket_pages/user/account/settings/metatrader');
var self_exclusion = require('./binary/websocket_pages/user/account/settings/self_exclusion');
var settings_detailsws = require('./binary/websocket_pages/user/account/settings/settings_detailsws');
var settings_securityws = require('./binary/websocket_pages/user/account/settings/settings_securityws');
var settings = require('./binary/websocket_pages/user/account/settings');
var statement_data = require('./binary/websocket_pages/user/account/statement/statement.data');
var statement_init = require('./binary/websocket_pages/user/account/statement/statement.init');
var statement_ui = require('./binary/websocket_pages/user/account/statement/statement.ui');
var statement = require('./binary/websocket_pages/user/account/statement');
var top_up_virtualws = require('./binary/websocket_pages/user/account/top_up_virtualws');
var lost_password_init = require('./binary/websocket_pages/user/lost_password/lost_password.init');
var lost_password = require('./binary/websocket_pages/user/lost_password');
var my_accountws = require('./binary/websocket_pages/user/my_accountws');
var financial_acc_opening_data = require('./binary/websocket_pages/user/new_account/financial_acc_opening/financial_acc_opening.data');
var financial_acc_opening_ui = require('./binary/websocket_pages/user/new_account/financial_acc_opening/financial_acc_opening.ui');
var financial_acc_opening = require('./binary/websocket_pages/user/new_account/financial_acc_opening');
var japan_acc_opening_data = require('./binary/websocket_pages/user/new_account/japan_acc_opening/japan_acc_opening.data');
var japan_acc_opening_ui = require('./binary/websocket_pages/user/new_account/japan_acc_opening/japan_acc_opening.ui');
var japan_acc_opening = require('./binary/websocket_pages/user/new_account/japan_acc_opening');
var real_acc_opening_data = require('./binary/websocket_pages/user/new_account/real_acc_opening/real_acc_opening.data');
var real_acc_opening_ui = require('./binary/websocket_pages/user/new_account/real_acc_opening/real_acc_opening.ui');
var real_acc_opening = require('./binary/websocket_pages/user/new_account/real_acc_opening');
var virtual_acc_opening_data = require('./binary/websocket_pages/user/new_account/virtual_acc_opening/virtual_acc_opening.data');
var virtual_acc_opening = require('./binary/websocket_pages/user/new_account/virtual_acc_opening');
var reality_check_data = require('./binary/websocket_pages/user/reality_check/reality_check.data');
var reality_check_init = require('./binary/websocket_pages/user/reality_check/reality_check.init');
var reality_check_ui = require('./binary/websocket_pages/user/reality_check/reality_check.ui');
var reset_password_init = require('./binary/websocket_pages/user/reset_password/reset_password.init');
var reset_password = require('./binary/websocket_pages/user/reset_password');
var tnc_approval = require('./binary/websocket_pages/user/tnc_approval');
var verify_email = require('./binary/websocket_pages/user/verify_email');
var view_popup_ui = require('./binary/websocket_pages/user/view_popup/view_popup_ui');
var view_popupws = require('./binary/websocket_pages/user/view_popup/view_popupws');
var viewbalance_init = require('./binary/websocket_pages/user/viewbalance/viewbalance.init');
var viewbalance_ui = require('./binary/websocket_pages/user/viewbalance/viewbalance.ui');
var websocket_pjax = require('./binary/websocket_pages/websocket_pjax');
var knowledge_test_data = require('./binary_japan/knowledge_test/knowledge_test.data');
var knowledge_test_init = require('./binary_japan/knowledge_test/knowledge_test.init');
var knowledge_test_ui = require('./binary_japan/knowledge_test/knowledge_test.ui');
var knowledge_test = require('./binary_japan/knowledge_test');
var JPTradePage = require('./binary_japan/trade_japan/JPTradePage');
var portfolio_jp = require('./binary_japan/trade_japan/portfolio');
var pricing_details = require('./binary_japan/trade_japan/pricing_details');

// TODO: to be remove after webpack finalized
var exportAllFunctions = function exportAllFunctions(obj) {
    for ( var key in obj ) {
        if ( obj.hasOwnProperty(key) ) {
            window[key] = obj[key];
        }
    }
};

exportAllFunctions(config);
exportAllFunctions(pjax);

exportAllFunctions(logged_in);
exportAllFunctions(login);
exportAllFunctions(markets);
exportAllFunctions(menu_content);
exportAllFunctions(onerror);
exportAllFunctions(page);
exportAllFunctions(storage);
exportAllFunctions(utility);
exportAllFunctions(base);
exportAllFunctions(active_symbols);
exportAllFunctions(button);
exportAllFunctions(flextable);
exportAllFunctions(password_strength_meter);
exportAllFunctions(table);
exportAllFunctions(common_data);
exportAllFunctions(currency_to_symbol);
exportAllFunctions(event_handler);
exportAllFunctions(frontend);
exportAllFunctions(get_app_details);
exportAllFunctions(guide);
exportAllFunctions(passwordmeter);
exportAllFunctions(risk_classification);
exportAllFunctions(session_duration_limit);
exportAllFunctions(string_util);
exportAllFunctions(traffic_source);
exportAllFunctions(valid_account_opening);
exportAllFunctions(validation);
exportAllFunctions(validation_v2);
exportAllFunctions(selected_dates);
exportAllFunctions(date_picker);
exportAllFunctions(time_picker);
exportAllFunctions(trackjs_onerror);
exportAllFunctions(get_started_jp);
exportAllFunctions(job_details);
exportAllFunctions(static_pjax);
exportAllFunctions(validator);
exportAllFunctions(account_transferws);
exportAllFunctions(cashier);
exportAllFunctions(deposit_withdraw_ws);
exportAllFunctions(payment_agent_listws);
exportAllFunctions(payment_agent_withdrawws);
exportAllFunctions(asset_indexws_data);
exportAllFunctions(asset_indexws_ui);
exportAllFunctions(asset_indexws);
exportAllFunctions(market_timesws_data);
exportAllFunctions(market_timesws_ui);
exportAllFunctions(market_timesws);
exportAllFunctions(socket);
exportAllFunctions(analysis);
exportAllFunctions(barriers);
exportAllFunctions(digit_infows);
exportAllFunctions(highchartws);
exportAllFunctions(common);
exportAllFunctions(content);
exportAllFunctions(contract);
exportAllFunctions(currency);
exportAllFunctions(defaults);
exportAllFunctions(duration);
exportAllFunctions(event_);
exportAllFunctions(message);
exportAllFunctions(price);
exportAllFunctions(process_);
exportAllFunctions(purchase);
exportAllFunctions(starttime);
exportAllFunctions(symbols);
exportAllFunctions(tick);
exportAllFunctions(tick_trade);
exportAllFunctions(tradepage);
exportAllFunctions(authenticate);
exportAllFunctions(change_password);
exportAllFunctions(payment_agent_transfer_data);
exportAllFunctions(payment_agent_transfer_init);
exportAllFunctions(payment_agent_transfer_ui);
exportAllFunctions(payment_agent_transfer);
exportAllFunctions(portfolio_init);
exportAllFunctions(portfolio);
exportAllFunctions(profit_table_data);
exportAllFunctions(profit_table_init);
exportAllFunctions(profit_table_ui);
exportAllFunctions(profit_table);
exportAllFunctions(api_token);
exportAllFunctions(authorised_apps_data);
exportAllFunctions(authorised_apps_init);
exportAllFunctions(authorised_apps_ui);
exportAllFunctions(authorised_apps);
exportAllFunctions(financial_assessment);
exportAllFunctions(iphistory_data);
exportAllFunctions(iphistory_init);
exportAllFunctions(iphistory_ui);
exportAllFunctions(iphistory);
exportAllFunctions(limits_init);
exportAllFunctions(limits_ui);
exportAllFunctions(limits);
exportAllFunctions(metatrader_data);
exportAllFunctions(metatrader_ui);
exportAllFunctions(metatrader);
exportAllFunctions(self_exclusion);
exportAllFunctions(settings_detailsws);
exportAllFunctions(settings_securityws);
exportAllFunctions(settings);
exportAllFunctions(statement_data);
exportAllFunctions(statement_init);
exportAllFunctions(statement_ui);
exportAllFunctions(statement);
exportAllFunctions(top_up_virtualws);
exportAllFunctions(lost_password_init);
exportAllFunctions(lost_password);
exportAllFunctions(my_accountws);
exportAllFunctions(financial_acc_opening_data);
exportAllFunctions(financial_acc_opening_ui);
exportAllFunctions(financial_acc_opening);
exportAllFunctions(japan_acc_opening_data);
exportAllFunctions(japan_acc_opening_ui);
exportAllFunctions(japan_acc_opening);
exportAllFunctions(real_acc_opening_data);
exportAllFunctions(real_acc_opening_ui);
exportAllFunctions(real_acc_opening);
exportAllFunctions(virtual_acc_opening_data);
exportAllFunctions(virtual_acc_opening);
exportAllFunctions(reality_check_data);
exportAllFunctions(reality_check_init);
exportAllFunctions(reality_check_ui);
exportAllFunctions(reset_password_init);
exportAllFunctions(reset_password);
exportAllFunctions(tnc_approval);
exportAllFunctions(verify_email);
exportAllFunctions(view_popup_ui);
exportAllFunctions(view_popupws);
exportAllFunctions(viewbalance_init);
exportAllFunctions(viewbalance_ui);
exportAllFunctions(websocket_pjax);
exportAllFunctions(knowledge_test_data);
exportAllFunctions(knowledge_test_init);
exportAllFunctions(knowledge_test_ui);
exportAllFunctions(knowledge_test);
exportAllFunctions(JPTradePage);
exportAllFunctions(portfolio_jp);
exportAllFunctions(pricing_details);

// module.exports = {
//     config: config,
//     pjax: pjax,
//     exportAllFunctions: exportAllFunctions,
// };
