// TODO: to be remove after webpack finalized
var exportAllFunctions = function exportAllFunctions(obj) {
    for ( var key in obj ) {
        if ( obj.hasOwnProperty(key) ) {
            window[key] = obj[key];
        }
    }
};

var logged_in = require('./binary/base/logged_in');
exportAllFunctions(logged_in);
var login = require('./binary/base/login');
exportAllFunctions(login);
var markets = require('./binary/base/markets');
exportAllFunctions(markets);
var menu_content = require('./binary/base/menu_content');
exportAllFunctions(menu_content);
var onerror = require('./binary/base/onerror');
exportAllFunctions(onerror);

var utility = require('./binary/base/utility');
exportAllFunctions(utility);
var storage = require('./binary/base/storage');
exportAllFunctions(storage);
var page = require('./binary/base/page');
exportAllFunctions(page);
var pjax = require('./binary/base/pjax');
exportAllFunctions(pjax);
var endpoint = require('./binary/static_pages/endpoint');
exportAllFunctions(endpoint);
var traffic_source = require('./binary/common_functions/traffic_source');
exportAllFunctions(traffic_source);

var KnowledgeTestData = require('./binary_japan/knowledge_test/knowledge_test.data.js');
exportAllFunctions(KnowledgeTestData);
var KnowledgeTest = require('./binary_japan/knowledge_test/knowledge_test.init.js');
exportAllFunctions(KnowledgeTest);
var KnowledgeTestUI = require('./binary_japan/knowledge_test/knowledge_test.ui.js');
exportAllFunctions(KnowledgeTestUI);
var JPTradePage = require('./binary_japan/trade_japan/JPTradePage.js');
exportAllFunctions(JPTradePage);
var JapanPortfolio = require('./binary_japan/trade_japan/portfolio.js');
exportAllFunctions(JapanPortfolio);
var PricingDetails = require('./binary_japan/trade_japan/pricing_details.js');
exportAllFunctions(PricingDetails);
var active_symbols = require('./binary/common_functions/active_symbols');
exportAllFunctions(active_symbols);
var button = require('./binary/common_functions/attach_dom/button');
exportAllFunctions(button);
var flextable = require('./binary/common_functions/attach_dom/flextable');
exportAllFunctions(flextable);
var password_strength_meter = require('./binary/common_functions/attach_dom/password_strength_meter');
exportAllFunctions(password_strength_meter);
var table = require('./binary/common_functions/attach_dom/table');
exportAllFunctions(table);
var common_data = require('./binary/common_functions/common_data');
exportAllFunctions(common_data);
var currency_to_symbol = require('./binary/common_functions/currency_to_symbol');
exportAllFunctions(currency_to_symbol);
var event_handler = require('./binary/common_functions/event_handler');
exportAllFunctions(event_handler);
var frontend = require('./binary/common_functions/frontend');
exportAllFunctions(frontend);
var get_app_details = require('./binary/common_functions/get_app_details');
exportAllFunctions(get_app_details);
var guide = require('./binary/common_functions/guide');
exportAllFunctions(guide);
var passwordmeter = require('./binary/common_functions/passwordmeter');
exportAllFunctions(passwordmeter);
var risk_classification = require('./binary/common_functions/risk_classification');
exportAllFunctions(risk_classification);
var session_duration_limit = require('./binary/common_functions/session_duration_limit');
exportAllFunctions(session_duration_limit);
var string_util = require('./binary/common_functions/string_util');
exportAllFunctions(string_util);
var valid_account_opening = require('./binary/common_functions/valid_account_opening');
exportAllFunctions(valid_account_opening);
var validation = require('./binary/common_functions/validation');
exportAllFunctions(validation);
var validation_v2 = require('./binary/common_functions/validation_v2');
exportAllFunctions(validation_v2);
var get_started_jp = require('./binary/static_pages/get_started_jp');
exportAllFunctions(get_started_jp);
var job_details = require('./binary/static_pages/job_details');
exportAllFunctions(job_details);

var content = require('./binary/websocket_pages/trade/content');
exportAllFunctions(content);
var verify_email = require('./binary/websocket_pages/user/verify_email');
exportAllFunctions(verify_email);
var static_pjax = require('./binary/static_pages/static_pjax');
exportAllFunctions(static_pjax);

var validator = require('./binary/validator');
exportAllFunctions(validator);
var account_transferws = require('./binary/websocket_pages/cashier/account_transferws');
exportAllFunctions(account_transferws);
var cashier = require('./binary/websocket_pages/cashier/cashier');
exportAllFunctions(cashier);
var deposit_withdraw_ws = require('./binary/websocket_pages/cashier/deposit_withdraw_ws');
exportAllFunctions(deposit_withdraw_ws);
var payment_agent_listws = require('./binary/websocket_pages/cashier/payment_agent_listws');
exportAllFunctions(payment_agent_listws);
var payment_agent_withdrawws = require('./binary/websocket_pages/cashier/payment_agent_withdrawws');
exportAllFunctions(payment_agent_withdrawws);
var asset_indexws_data = require('./binary/websocket_pages/resources/asset_index/asset_indexws.data');
exportAllFunctions(asset_indexws_data);
var asset_indexws_ui = require('./binary/websocket_pages/resources/asset_index/asset_indexws.ui');
exportAllFunctions(asset_indexws_ui);
var asset_indexws = require('./binary/websocket_pages/resources/asset_indexws');
exportAllFunctions(asset_indexws);
var market_timesws_data = require('./binary/websocket_pages/resources/market_times/market_timesws.data');
exportAllFunctions(market_timesws_data);
var market_timesws_ui = require('./binary/websocket_pages/resources/market_times/market_timesws.ui');
exportAllFunctions(market_timesws_ui);
var market_timesws = require('./binary/websocket_pages/resources/market_timesws');
exportAllFunctions(market_timesws);
var socket = require('./binary/websocket_pages/socket');
exportAllFunctions(socket);
var analysis = require('./binary/websocket_pages/trade/analysis');
exportAllFunctions(analysis);
var barriers = require('./binary/websocket_pages/trade/barriers');
exportAllFunctions(barriers);
var digit_infows = require('./binary/websocket_pages/trade/charts/digit_infows');
exportAllFunctions(digit_infows);
var highchartws = require('./binary/websocket_pages/trade/charts/highchartws');
exportAllFunctions(highchartws);
var common = require('./binary/websocket_pages/trade/common');
exportAllFunctions(common);
var contract = require('./binary/websocket_pages/trade/contract');
exportAllFunctions(contract);
var currency = require('./binary/websocket_pages/trade/currency');
exportAllFunctions(currency);
var defaults = require('./binary/websocket_pages/trade/defaults');
exportAllFunctions(defaults);
var duration = require('./binary/websocket_pages/trade/duration');
exportAllFunctions(duration);
var event_ = require('./binary/websocket_pages/trade/event');
exportAllFunctions(event_);
var message = require('./binary/websocket_pages/trade/message');
exportAllFunctions(message);
var price = require('./binary/websocket_pages/trade/price');
exportAllFunctions(price);
var process_ = require('./binary/websocket_pages/trade/process');
exportAllFunctions(process_);
var purchase = require('./binary/websocket_pages/trade/purchase');
exportAllFunctions(purchase);
var starttime = require('./binary/websocket_pages/trade/starttime');
exportAllFunctions(starttime);
var symbols = require('./binary/websocket_pages/trade/symbols');
exportAllFunctions(symbols);
var tick = require('./binary/websocket_pages/trade/tick');
exportAllFunctions(tick);
var tick_trade = require('./binary/websocket_pages/trade/tick_trade');
exportAllFunctions(tick_trade);
var tradepage = require('./binary/websocket_pages/trade/tradepage');
exportAllFunctions(tradepage);
var authenticate = require('./binary/websocket_pages/user/account/authenticate');
exportAllFunctions(authenticate);
var change_password = require('./binary/websocket_pages/user/account/change_password');
exportAllFunctions(change_password);
var payment_agent_transfer_data = require('./binary/websocket_pages/user/account/payment_agent_transfer/payment_agent_transfer.data');
exportAllFunctions(payment_agent_transfer_data);
var payment_agent_transfer_init = require('./binary/websocket_pages/user/account/payment_agent_transfer/payment_agent_transfer.init');
exportAllFunctions(payment_agent_transfer_init);
var payment_agent_transfer_ui = require('./binary/websocket_pages/user/account/payment_agent_transfer/payment_agent_transfer.ui');
exportAllFunctions(payment_agent_transfer_ui);
var payment_agent_transfer = require('./binary/websocket_pages/user/account/payment_agent_transfer');
exportAllFunctions(payment_agent_transfer);
var portfolio_init = require('./binary/websocket_pages/user/account/portfolio/portfolio.init');
exportAllFunctions(portfolio_init);
var portfolio = require('./binary/websocket_pages/user/account/portfolio');
exportAllFunctions(portfolio);
var profit_table_data = require('./binary/websocket_pages/user/account/profit_table/profit_table.data');
exportAllFunctions(profit_table_data);
var profit_table_init = require('./binary/websocket_pages/user/account/profit_table/profit_table.init');
exportAllFunctions(profit_table_init);
var profit_table_ui = require('./binary/websocket_pages/user/account/profit_table/profit_table.ui');
exportAllFunctions(profit_table_ui);
var profit_table = require('./binary/websocket_pages/user/account/profit_table');
exportAllFunctions(profit_table);
var api_token = require('./binary/websocket_pages/user/account/settings/api_token');
exportAllFunctions(api_token);
var authorised_apps_data = require('./binary/websocket_pages/user/account/settings/authorised_apps/authorised_apps.data');
exportAllFunctions(authorised_apps_data);
var authorised_apps_init = require('./binary/websocket_pages/user/account/settings/authorised_apps/authorised_apps.init');
exportAllFunctions(authorised_apps_init);
var authorised_apps_ui = require('./binary/websocket_pages/user/account/settings/authorised_apps/authorised_apps.ui');
exportAllFunctions(authorised_apps_ui);
var authorised_apps = require('./binary/websocket_pages/user/account/settings/authorised_apps');
exportAllFunctions(authorised_apps);
var financial_assessment = require('./binary/websocket_pages/user/account/settings/financial_assessment');
exportAllFunctions(financial_assessment);
var iphistory_data = require('./binary/websocket_pages/user/account/settings/iphistory/iphistory.data');
exportAllFunctions(iphistory_data);
var iphistory_init = require('./binary/websocket_pages/user/account/settings/iphistory/iphistory.init');
exportAllFunctions(iphistory_init);
var iphistory_ui = require('./binary/websocket_pages/user/account/settings/iphistory/iphistory.ui');
exportAllFunctions(iphistory_ui);
var iphistory = require('./binary/websocket_pages/user/account/settings/iphistory');
exportAllFunctions(iphistory);
var limits_init = require('./binary/websocket_pages/user/account/settings/limits/limits.init');
exportAllFunctions(limits_init);
var limits_ui = require('./binary/websocket_pages/user/account/settings/limits/limits.ui');
exportAllFunctions(limits_ui);
var limits = require('./binary/websocket_pages/user/account/settings/limits');
exportAllFunctions(limits);
var metatrader_data = require('./binary/websocket_pages/user/account/settings/metatrader/metatrader.data');
exportAllFunctions(metatrader_data);
var metatrader_ui = require('./binary/websocket_pages/user/account/settings/metatrader/metatrader.ui');
exportAllFunctions(metatrader_ui);
var metatrader = require('./binary/websocket_pages/user/account/settings/metatrader');
exportAllFunctions(metatrader);
var self_exclusion = require('./binary/websocket_pages/user/account/settings/self_exclusion');
exportAllFunctions(self_exclusion);
var settings_detailsws = require('./binary/websocket_pages/user/account/settings/settings_detailsws');
exportAllFunctions(settings_detailsws);
var settings_securityws = require('./binary/websocket_pages/user/account/settings/settings_securityws');
exportAllFunctions(settings_securityws);
var settings = require('./binary/websocket_pages/user/account/settings');
exportAllFunctions(settings);
var statement_data = require('./binary/websocket_pages/user/account/statement/statement.data');
exportAllFunctions(statement_data);
var statement_init = require('./binary/websocket_pages/user/account/statement/statement.init');
exportAllFunctions(statement_init);
var statement_ui = require('./binary/websocket_pages/user/account/statement/statement.ui');
exportAllFunctions(statement_ui);
var statement = require('./binary/websocket_pages/user/account/statement');
exportAllFunctions(statement);
var top_up_virtualws = require('./binary/websocket_pages/user/account/top_up_virtualws');
exportAllFunctions(top_up_virtualws);
var lost_password_init = require('./binary/websocket_pages/user/lost_password/lost_password.init');
exportAllFunctions(lost_password_init);
var lost_password = require('./binary/websocket_pages/user/lost_password');
exportAllFunctions(lost_password);
var my_accountws = require('./binary/websocket_pages/user/my_accountws');
exportAllFunctions(my_accountws);
var financial_acc_opening_data = require('./binary/websocket_pages/user/new_account/financial_acc_opening/financial_acc_opening.data');
exportAllFunctions(financial_acc_opening_data);
var financial_acc_opening_ui = require('./binary/websocket_pages/user/new_account/financial_acc_opening/financial_acc_opening.ui');
exportAllFunctions(financial_acc_opening_ui);
var financial_acc_opening = require('./binary/websocket_pages/user/new_account/financial_acc_opening');
exportAllFunctions(financial_acc_opening);
var japan_acc_opening_data = require('./binary/websocket_pages/user/new_account/japan_acc_opening/japan_acc_opening.data');
exportAllFunctions(japan_acc_opening_data);
var japan_acc_opening_ui = require('./binary/websocket_pages/user/new_account/japan_acc_opening/japan_acc_opening.ui');
exportAllFunctions(japan_acc_opening_ui);
var japan_acc_opening = require('./binary/websocket_pages/user/new_account/japan_acc_opening');
exportAllFunctions(japan_acc_opening);
var real_acc_opening_data = require('./binary/websocket_pages/user/new_account/real_acc_opening/real_acc_opening.data');
exportAllFunctions(real_acc_opening_data);
var real_acc_opening_ui = require('./binary/websocket_pages/user/new_account/real_acc_opening/real_acc_opening.ui');
exportAllFunctions(real_acc_opening_ui);
var real_acc_opening = require('./binary/websocket_pages/user/new_account/real_acc_opening');
exportAllFunctions(real_acc_opening);
var virtual_acc_opening_data = require('./binary/websocket_pages/user/new_account/virtual_acc_opening/virtual_acc_opening.data');
exportAllFunctions(virtual_acc_opening_data);
var virtual_acc_opening = require('./binary/websocket_pages/user/new_account/virtual_acc_opening');
exportAllFunctions(virtual_acc_opening);
var reality_check_data = require('./binary/websocket_pages/user/reality_check/reality_check.data');
exportAllFunctions(reality_check_data);
var reality_check_init = require('./binary/websocket_pages/user/reality_check/reality_check.init');
exportAllFunctions(reality_check_init);
var reality_check_ui = require('./binary/websocket_pages/user/reality_check/reality_check.ui');
exportAllFunctions(reality_check_ui);
var reset_password_init = require('./binary/websocket_pages/user/reset_password/reset_password.init');
exportAllFunctions(reset_password_init);
var reset_password = require('./binary/websocket_pages/user/reset_password');
exportAllFunctions(reset_password);
var tnc_approval = require('./binary/websocket_pages/user/tnc_approval');
exportAllFunctions(tnc_approval);
var view_popup_ui = require('./binary/websocket_pages/user/view_popup/view_popup_ui');
exportAllFunctions(view_popup_ui);
var view_popupws = require('./binary/websocket_pages/user/view_popup/view_popupws');
exportAllFunctions(view_popupws);
var viewbalance_init = require('./binary/websocket_pages/user/viewbalance/viewbalance.init');
exportAllFunctions(viewbalance_init);
var viewbalance_ui = require('./binary/websocket_pages/user/viewbalance/viewbalance.ui');
exportAllFunctions(viewbalance_ui);
var websocket_pjax = require('./binary/websocket_pages/websocket_pjax');
exportAllFunctions(websocket_pjax);
var knowledge_test_data = require('./binary_japan/knowledge_test/knowledge_test.data');
exportAllFunctions(knowledge_test_data);
var knowledge_test_init = require('./binary_japan/knowledge_test/knowledge_test.init');
exportAllFunctions(knowledge_test_init);
var knowledge_test_ui = require('./binary_japan/knowledge_test/knowledge_test.ui');
exportAllFunctions(knowledge_test_ui);
var knowledge_test = require('./binary_japan/knowledge_test');
exportAllFunctions(knowledge_test);
var JPTradePage = require('./binary_japan/trade_japan/JPTradePage');
exportAllFunctions(JPTradePage);
var portfolio = require('./binary_japan/trade_japan/portfolio');
exportAllFunctions(portfolio);
var pricing_details = require('./binary_japan/trade_japan/pricing_details');
exportAllFunctions(pricing_details);
var config = require('./config');
exportAllFunctions(config);
