#!/bin/sh

DIR=$(cd "$(dirname "$0")"; pwd)
cd "$DIR"
echo "Update translated text for js\n";

carton exec perl -Ilib -Ibin -MGenerateStaticData -e "GenerateStaticData::generate_japan_data_files('../../japanui/src/js/autogenerated')"
